package com.jp.sense.pr.dao;

import java.util.List;

import com.jp.sense.pr.model.dto.BrowsingHistoryDTO;
import com.jp.sense.pr.model.entity.BrowsingHistory;
import com.jp.sense.pr.model.entity.BrowsingHistoryKey;

public interface BrowsingHistoryDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table browsing_history
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(BrowsingHistoryKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table browsing_history
	 * @mbg.generated
	 */
	int insert(BrowsingHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table browsing_history
	 * @mbg.generated
	 */
	int insertSelective(BrowsingHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table browsing_history
	 * @mbg.generated
	 */
	BrowsingHistory selectByPrimaryKey(BrowsingHistoryKey key);

	/**
	 * Gets all browsing history for the specified media user.
	 * 
	 * @param mediaUserId
	 * @return browsing history list
	 */
	List<BrowsingHistoryDTO> selectByMediaUserId(Integer mediaUserId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table browsing_history
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(BrowsingHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table browsing_history
	 * @mbg.generated
	 */
	int updateByPrimaryKey(BrowsingHistory record);
}