package com.jp.sense.pr.dao;

import org.apache.ibatis.annotations.Param;

import com.jp.sense.pr.model.entity.Company;

public interface CompanyDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbg.generated
	 */
	int insert(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbg.generated
	 */
	int insertSelective(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbg.generated
	 */
	Company selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Company record);

	/**
     * --企業テーブルの料金プランを保存
     * @param id
     * @return
     */	
	 int updateServicePlanOfCompany(@Param("serviceId") Integer serviceId, @Param("planCat") String planCat, @Param("companyId") Integer companyId);
}