package com.jp.sense.pr.dao;

import com.jp.sense.pr.model.dto.PressReleaseCompMediaListDTO;
import com.jp.sense.pr.model.entity.CompMediaList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CompMediaListDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_media_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("companyId") Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_media_list
     *
     * @mbg.generated
     */
    int insert(CompMediaList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_media_list
     *
     * @mbg.generated
     */
    int insertSelective(CompMediaList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_media_list
     *
     * @mbg.generated
     */
    CompMediaList selectByPrimaryKey(@Param("id") Integer id, @Param("companyId") Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_media_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CompMediaList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_media_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompMediaList record);
    
    /**
	 * -PR検索
	 * 
	 * @author 朱
	 */
	List<PressReleaseCompMediaListDTO> selectPressReleaseCompMediaList(@Param("cid") Integer cid, @Param("pageStartCount") Integer pageStartCount, @Param("pageCount") Integer pageCount);
	
	/**
	 * -PR検索
	 * 
	 * @author 朱
	 */
	int updatePrDeleteFlag(Integer prid);
}