package com.jp.sense.pr.dao;

import com.jp.sense.pr.model.entity.CorporatecontractList;
import com.jp.sense.pr.model.entity.CorporatecontractListKey;

public interface CorporateContractListDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table corporateContract_list
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(CorporatecontractListKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table corporateContract_list
	 * @mbg.generated
	 */
	int insert(CorporatecontractList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table corporateContract_list
	 * @mbg.generated
	 */
	int insertSelective(CorporatecontractList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table corporateContract_list
	 * @mbg.generated
	 */
	CorporatecontractList selectByPrimaryKey(CorporatecontractListKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table corporateContract_list
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(CorporatecontractList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table corporateContract_list
	 * @mbg.generated
	 */
	int updateByPrimaryKey(CorporatecontractList record);   
}