package com.jp.sense.pr.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import com.jp.sense.pr.model.entity.MasterManagement;

public interface MasterManagementDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_management
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_management
     *
     * @mbg.generated
     */
    int insert(MasterManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_management
     *
     * @mbg.generated
     */
    int insertSelective(MasterManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_management
     *
     * @mbg.generated
     */
    MasterManagement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_management
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MasterManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_management
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MasterManagement record);
    
	/**
	 * --メディア種類リストを取得する
	 * 
	 * @author ネィ
	 */
	List<MasterManagement> selectMediaTypes(Integer id);
	
	/**
	 * --メディア種類IDを取得する
	 * 
	 * @author ネィ
	 */
	int selectMediaTypeID(String name);
    /**
	 *	共通関数：親と全ての子マスタデータを取得
	 * @author Li
	 */
    List<MasterManagement> getAbsoluteChildren(@Param("pid") Integer pid);
    
}