package com.jp.sense.pr.dao;

import org.apache.ibatis.annotations.Param;
import java.util.List;

import com.jp.sense.pr.model.entity.MediaUser;

public interface MediaUserDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_user
	 * @mbg.generated
	 */
	int insert(MediaUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_user
	 * @mbg.generated
	 */
	int insertSelective(MediaUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_user
	 * @mbg.generated
	 */
	MediaUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_user
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MediaUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MediaUser record);

	/**
     *	認証用ユーザ取得関数
     *	author: Li
     */
    List<MediaUser> selectByEmail(String email);

	/**
     *	パスワード再設定
     *	@author 山口
     */    
    int updateMediaUserPassword(@Param("id") Integer id, @Param("resetPassword") String resetPassword);
}