package com.jp.sense.pr.dao;

import java.util.List;

import com.jp.sense.pr.model.entity.NotificationManage;

public interface NotificationManageDao {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notification_manage
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notification_manage
	 * @mbg.generated
	 */
	int insert(NotificationManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notification_manage
	 * @mbg.generated
	 */
	int insertSelective(NotificationManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notification_manage
	 * @mbg.generated
	 */
	NotificationManage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notification_manage
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(NotificationManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notification_manage
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(NotificationManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notification_manage
	 * @mbg.generated
	 */
	int updateByPrimaryKey(NotificationManage record);

	/**
	 * --お知らせ情報を取得する
	 * 
	 * @author ネィ
	 */
	List<NotificationManage> selectNotifyListForHomePage();
}