package com.jp.sense.pr.dao;

import com.jp.sense.pr.model.entity.OperatorInfo;

public interface OperatorInfoDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table operator_info
	 * @mbg.generated
	 */
	int insert(OperatorInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table operator_info
	 * @mbg.generated
	 */
	int insertSelective(OperatorInfo record);
}