package com.jp.sense.pr.dao;

import com.jp.sense.pr.model.entity.Prefectures;

public interface PrefecturesDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prefectures
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prefectures
	 * @mbg.generated
	 */
	int insert(Prefectures record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prefectures
	 * @mbg.generated
	 */
	int insertSelective(Prefectures record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prefectures
	 * @mbg.generated
	 */
	Prefectures selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prefectures
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Prefectures record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prefectures
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Prefectures record);

	/**
	 * zip >> address
	 * @author:Li
	 */
	Prefectures selectByZipCode(String zipCd);

}