package com.jp.sense.pr.dao;

import com.jp.sense.pr.model.entity.PressReleaseImage;
import com.jp.sense.pr.model.entity.PressReleaseImageKey;

public interface PressReleaseImageDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_image
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(PressReleaseImageKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_image
	 * @mbg.generated
	 */
	int insert(PressReleaseImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_image
	 * @mbg.generated
	 */
	int insertSelective(PressReleaseImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_image
	 * @mbg.generated
	 */
	PressReleaseImage selectByPrimaryKey(PressReleaseImageKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_image
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PressReleaseImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_image
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PressReleaseImage record);
}