package com.jp.sense.pr.dao;

import com.jp.sense.pr.model.entity.PressReleaseAccessHistory;
import com.jp.sense.pr.model.entity.PressReleaseAccessHistoryKey;

public interface PressReleaseAccessHistoryDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_access_history
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(PressReleaseAccessHistoryKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_access_history
	 * @mbg.generated
	 */
	int insert(PressReleaseAccessHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_access_history
	 * @mbg.generated
	 */
	int insertSelective(PressReleaseAccessHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_access_history
	 * @mbg.generated
	 */
	PressReleaseAccessHistory selectByPrimaryKey(PressReleaseAccessHistoryKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_access_history
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PressReleaseAccessHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_access_history
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PressReleaseAccessHistory record);
}