package com.jp.sense.pr.dao;

import java.util.List;

import com.jp.sense.pr.model.entity.ServicePlan;

public interface ServicePlanDao {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_plan
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_plan
	 * @mbg.generated
	 */
	int insert(ServicePlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_plan
	 * @mbg.generated
	 */
	int insertSelective(ServicePlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_plan
	 * @mbg.generated
	 */
	ServicePlan selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_plan
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ServicePlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_plan
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ServicePlan record);

	/**
     * --企業の料金プランを取得する。
     * @param id
     * @return
     */
    List<ServicePlan> selectServicePlan();
    
	/**
     * --変更する企業の料金プラン詳細取得する。
     * 
     * @param id
     * @return
     */
    ServicePlan selectServicePlanChange(Integer serviceId);

	/**
	 * --従量課金を取得する
	 * 
	 * @author 山内
	 */
	List<ServicePlan> selectPayAsUgoPlan();

	/**
	 * --定額プランを取得する
	 * 
	 * @author 山内
	 */
	List<ServicePlan> selectFlatRatePlan();
}