package com.jp.sense.pr.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table browsing_history
 */
public class BrowsingHistory extends BrowsingHistoryKey {

	/**
	 * Database Column Remarks: 削除フラグ This field was generated by MyBatis Generator. This field corresponds to the database column browsing_history.delete_flag
	 * @mbg.generated
	 */
	private String deleteFlag;
	/**
	 * Database Column Remarks: 作成者 This field was generated by MyBatis Generator. This field corresponds to the database column browsing_history.create_user
	 * @mbg.generated
	 */
	private String createUser;
	/**
	 * Database Column Remarks: 作成日時:yyyy/MM/dd HH:mm:ss This field was generated by MyBatis Generator. This field corresponds to the database column browsing_history.create_datetime
	 * @mbg.generated
	 */
	private Date createDatetime;
	/**
	 * Database Column Remarks: 最終更新者 This field was generated by MyBatis Generator. This field corresponds to the database column browsing_history.update_user
	 * @mbg.generated
	 */
	private String updateUser;
	/**
	 * Database Column Remarks: 最終更新日時:yyyy/MM/dd HH:mm:ss This field was generated by MyBatis Generator. This field corresponds to the database column browsing_history.update_datetime
	 * @mbg.generated
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column browsing_history.delete_flag
	 * @return  the value of browsing_history.delete_flag
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column browsing_history.delete_flag
	 * @param deleteFlag  the value for browsing_history.delete_flag
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column browsing_history.create_user
	 * @return  the value of browsing_history.create_user
	 * @mbg.generated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column browsing_history.create_user
	 * @param createUser  the value for browsing_history.create_user
	 * @mbg.generated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column browsing_history.create_datetime
	 * @return  the value of browsing_history.create_datetime
	 * @mbg.generated
	 */
	public Date getCreateDatetime() {
		return createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column browsing_history.create_datetime
	 * @param createDatetime  the value for browsing_history.create_datetime
	 * @mbg.generated
	 */
	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column browsing_history.update_user
	 * @return  the value of browsing_history.update_user
	 * @mbg.generated
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column browsing_history.update_user
	 * @param updateUser  the value for browsing_history.update_user
	 * @mbg.generated
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column browsing_history.update_datetime
	 * @return  the value of browsing_history.update_datetime
	 * @mbg.generated
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column browsing_history.update_datetime
	 * @param updateDatetime  the value for browsing_history.update_datetime
	 * @mbg.generated
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table browsing_history
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", deleteFlag=").append(deleteFlag);
		sb.append(", createUser=").append(createUser);
		sb.append(", createDatetime=").append(createDatetime);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updateDatetime=").append(updateDatetime);
		sb.append("]");
		return sb.toString();
	}
}