package com.jp.sense.pr.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table comp_billing_info
 */
public class CompBillingInfo {
    /**
     * Database Column Remarks:
     *   企業ID:company
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   会社名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * Database Column Remarks:
     *   住所（郵便番号）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.billing_address1
     *
     * @mbg.generated
     */
    private String billingAddress1;

    /**
     * Database Column Remarks:
     *   住所（都道府県市区町村番地）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.billing_address2
     *
     * @mbg.generated
     */
    private String billingAddress2;

    /**
     * Database Column Remarks:
     *   住所（建物．階数）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.billing_address3
     *
     * @mbg.generated
     */
    private String billingAddress3;

    /**
     * Database Column Remarks:
     *   所属部署
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.billing_department
     *
     * @mbg.generated
     */
    private String billingDepartment;

    /**
     * Database Column Remarks:
     *   氏名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.billing_name
     *
     * @mbg.generated
     */
    private String billingName;

    /**
     * Database Column Remarks:
     *   氏名（カナ）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.billing_name_kana
     *
     * @mbg.generated
     */
    private String billingNameKana;

    /**
     * Database Column Remarks:
     *   メールアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.billing_email
     *
     * @mbg.generated
     */
    private String billingEmail;

    /**
     * Database Column Remarks:
     *   メールアドレス(cc)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.billing_email_cc
     *
     * @mbg.generated
     */
    private String billingEmailCc;

    /**
     * Database Column Remarks:
     *   削除フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.delete_flag
     *
     * @mbg.generated
     */
    private String deleteFlag;

    /**
     * Database Column Remarks:
     *   作成者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     * Database Column Remarks:
     *   作成日時:yyyy/MM/dd HH:mm:ss
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.create_datetime
     *
     * @mbg.generated
     */
    private Date createDatetime;

    /**
     * Database Column Remarks:
     *   最終更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * Database Column Remarks:
     *   最終更新日時:yyyy/MM/dd HH:mm:ss
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comp_billing_info.update_datetime
     *
     * @mbg.generated
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.id
     *
     * @return the value of comp_billing_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.id
     *
     * @param id the value for comp_billing_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.company_name
     *
     * @return the value of comp_billing_info.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.company_name
     *
     * @param companyName the value for comp_billing_info.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.billing_address1
     *
     * @return the value of comp_billing_info.billing_address1
     *
     * @mbg.generated
     */
    public String getBillingAddress1() {
        return billingAddress1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.billing_address1
     *
     * @param billingAddress1 the value for comp_billing_info.billing_address1
     *
     * @mbg.generated
     */
    public void setBillingAddress1(String billingAddress1) {
        this.billingAddress1 = billingAddress1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.billing_address2
     *
     * @return the value of comp_billing_info.billing_address2
     *
     * @mbg.generated
     */
    public String getBillingAddress2() {
        return billingAddress2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.billing_address2
     *
     * @param billingAddress2 the value for comp_billing_info.billing_address2
     *
     * @mbg.generated
     */
    public void setBillingAddress2(String billingAddress2) {
        this.billingAddress2 = billingAddress2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.billing_address3
     *
     * @return the value of comp_billing_info.billing_address3
     *
     * @mbg.generated
     */
    public String getBillingAddress3() {
        return billingAddress3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.billing_address3
     *
     * @param billingAddress3 the value for comp_billing_info.billing_address3
     *
     * @mbg.generated
     */
    public void setBillingAddress3(String billingAddress3) {
        this.billingAddress3 = billingAddress3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.billing_department
     *
     * @return the value of comp_billing_info.billing_department
     *
     * @mbg.generated
     */
    public String getBillingDepartment() {
        return billingDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.billing_department
     *
     * @param billingDepartment the value for comp_billing_info.billing_department
     *
     * @mbg.generated
     */
    public void setBillingDepartment(String billingDepartment) {
        this.billingDepartment = billingDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.billing_name
     *
     * @return the value of comp_billing_info.billing_name
     *
     * @mbg.generated
     */
    public String getBillingName() {
        return billingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.billing_name
     *
     * @param billingName the value for comp_billing_info.billing_name
     *
     * @mbg.generated
     */
    public void setBillingName(String billingName) {
        this.billingName = billingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.billing_name_kana
     *
     * @return the value of comp_billing_info.billing_name_kana
     *
     * @mbg.generated
     */
    public String getBillingNameKana() {
        return billingNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.billing_name_kana
     *
     * @param billingNameKana the value for comp_billing_info.billing_name_kana
     *
     * @mbg.generated
     */
    public void setBillingNameKana(String billingNameKana) {
        this.billingNameKana = billingNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.billing_email
     *
     * @return the value of comp_billing_info.billing_email
     *
     * @mbg.generated
     */
    public String getBillingEmail() {
        return billingEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.billing_email
     *
     * @param billingEmail the value for comp_billing_info.billing_email
     *
     * @mbg.generated
     */
    public void setBillingEmail(String billingEmail) {
        this.billingEmail = billingEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.billing_email_cc
     *
     * @return the value of comp_billing_info.billing_email_cc
     *
     * @mbg.generated
     */
    public String getBillingEmailCc() {
        return billingEmailCc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.billing_email_cc
     *
     * @param billingEmailCc the value for comp_billing_info.billing_email_cc
     *
     * @mbg.generated
     */
    public void setBillingEmailCc(String billingEmailCc) {
        this.billingEmailCc = billingEmailCc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.delete_flag
     *
     * @return the value of comp_billing_info.delete_flag
     *
     * @mbg.generated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.delete_flag
     *
     * @param deleteFlag the value for comp_billing_info.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.create_user
     *
     * @return the value of comp_billing_info.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.create_user
     *
     * @param createUser the value for comp_billing_info.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.create_datetime
     *
     * @return the value of comp_billing_info.create_datetime
     *
     * @mbg.generated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.create_datetime
     *
     * @param createDatetime the value for comp_billing_info.create_datetime
     *
     * @mbg.generated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.update_user
     *
     * @return the value of comp_billing_info.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.update_user
     *
     * @param updateUser the value for comp_billing_info.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comp_billing_info.update_datetime
     *
     * @return the value of comp_billing_info.update_datetime
     *
     * @mbg.generated
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comp_billing_info.update_datetime
     *
     * @param updateDatetime the value for comp_billing_info.update_datetime
     *
     * @mbg.generated
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_billing_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyName=").append(companyName);
        sb.append(", billingAddress1=").append(billingAddress1);
        sb.append(", billingAddress2=").append(billingAddress2);
        sb.append(", billingAddress3=").append(billingAddress3);
        sb.append(", billingDepartment=").append(billingDepartment);
        sb.append(", billingName=").append(billingName);
        sb.append(", billingNameKana=").append(billingNameKana);
        sb.append(", billingEmail=").append(billingEmail);
        sb.append(", billingEmailCc=").append(billingEmailCc);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", createUser=").append(createUser);
        sb.append(", createDatetime=").append(createDatetime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateDatetime=").append(updateDatetime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_billing_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CompBillingInfo other = (CompBillingInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getBillingAddress1() == null ? other.getBillingAddress1() == null : this.getBillingAddress1().equals(other.getBillingAddress1()))
            && (this.getBillingAddress2() == null ? other.getBillingAddress2() == null : this.getBillingAddress2().equals(other.getBillingAddress2()))
            && (this.getBillingAddress3() == null ? other.getBillingAddress3() == null : this.getBillingAddress3().equals(other.getBillingAddress3()))
            && (this.getBillingDepartment() == null ? other.getBillingDepartment() == null : this.getBillingDepartment().equals(other.getBillingDepartment()))
            && (this.getBillingName() == null ? other.getBillingName() == null : this.getBillingName().equals(other.getBillingName()))
            && (this.getBillingNameKana() == null ? other.getBillingNameKana() == null : this.getBillingNameKana().equals(other.getBillingNameKana()))
            && (this.getBillingEmail() == null ? other.getBillingEmail() == null : this.getBillingEmail().equals(other.getBillingEmail()))
            && (this.getBillingEmailCc() == null ? other.getBillingEmailCc() == null : this.getBillingEmailCc().equals(other.getBillingEmailCc()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateDatetime() == null ? other.getCreateDatetime() == null : this.getCreateDatetime().equals(other.getCreateDatetime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null : this.getUpdateDatetime().equals(other.getUpdateDatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_billing_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getBillingAddress1() == null) ? 0 : getBillingAddress1().hashCode());
        result = prime * result + ((getBillingAddress2() == null) ? 0 : getBillingAddress2().hashCode());
        result = prime * result + ((getBillingAddress3() == null) ? 0 : getBillingAddress3().hashCode());
        result = prime * result + ((getBillingDepartment() == null) ? 0 : getBillingDepartment().hashCode());
        result = prime * result + ((getBillingName() == null) ? 0 : getBillingName().hashCode());
        result = prime * result + ((getBillingNameKana() == null) ? 0 : getBillingNameKana().hashCode());
        result = prime * result + ((getBillingEmail() == null) ? 0 : getBillingEmail().hashCode());
        result = prime * result + ((getBillingEmailCc() == null) ? 0 : getBillingEmailCc().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateDatetime() == null) ? 0 : getCreateDatetime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
        return result;
    }
}