package com.jp.sense.pr.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table company
 */
public class Company {

	/**
	 * Database Column Remarks: 企業ID This field was generated by MyBatis Generator. This field corresponds to the database column company.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 法人名 This field was generated by MyBatis Generator. This field corresponds to the database column company.corporate_name
	 * @mbg.generated
	 */
	private String corporateName;
	/**
	 * Database Column Remarks: 法人名（カナ） This field was generated by MyBatis Generator. This field corresponds to the database column company.corporate_name_kana
	 * @mbg.generated
	 */
	private String corporateNameKana;
	/**
	 * Database Column Remarks: 代表者名 This field was generated by MyBatis Generator. This field corresponds to the database column company.representative_name
	 * @mbg.generated
	 */
	private String representativeName;
	/**
	 * Database Column Remarks: 代表者役職 This field was generated by MyBatis Generator. This field corresponds to the database column company.representative_position
	 * @mbg.generated
	 */
	private String representativePosition;
	/**
	 * Database Column Remarks: 法人設立年月 This field was generated by MyBatis Generator. This field corresponds to the database column company.establishment_date
	 * @mbg.generated
	 */
	private Date establishmentDate;
	/**
	 * Database Column Remarks: 本社所在地（郵便番号） This field was generated by MyBatis Generator. This field corresponds to the database column company.address1
	 * @mbg.generated
	 */
	private String address1;
	/**
	 * Database Column Remarks: 本社所在地（都道府県市区町村番地） This field was generated by MyBatis Generator. This field corresponds to the database column company.address2
	 * @mbg.generated
	 */
	private String address2;
	/**
	 * Database Column Remarks: 本社所在地（建物・階数） This field was generated by MyBatis Generator. This field corresponds to the database column company.address3
	 * @mbg.generated
	 */
	private String address3;
	/**
	 * Database Column Remarks: 代表電話番号 This field was generated by MyBatis Generator. This field corresponds to the database column company.representative_phone_no
	 * @mbg.generated
	 */
	private String representativePhoneNo;
	/**
	 * Database Column Remarks: 上場区分 This field was generated by MyBatis Generator. This field corresponds to the database column company.listing_category
	 * @mbg.generated
	 */
	private String listingCategory;
	/**
	 * Database Column Remarks: 証券コード This field was generated by MyBatis Generator. This field corresponds to the database column company.security_code
	 * @mbg.generated
	 */
	private String securityCode;
	/**
	 * Database Column Remarks: 資本金:単位：万円 This field was generated by MyBatis Generator. This field corresponds to the database column company.capital_amount
	 * @mbg.generated
	 */
	private String capitalAmount;
	/**
	 * Database Column Remarks: 社員数:単位：人 This field was generated by MyBatis Generator. This field corresponds to the database column company.num_of_employees
	 * @mbg.generated
	 */
	private String numOfEmployees;
	/**
	 * Database Column Remarks: サイトURL This field was generated by MyBatis Generator. This field corresponds to the database column company.site_url
	 * @mbg.generated
	 */
	private String siteUrl;
	/**
	 * Database Column Remarks: 業種区分:マスタテーブルFK This field was generated by MyBatis Generator. This field corresponds to the database column company.industry_category
	 * @mbg.generated
	 */
	private Integer industryCategory;
	/**
	 * Database Column Remarks: ビジネスカテゴリ1:マスタテーブルFK This field was generated by MyBatis Generator. This field corresponds to the database column company.company_category1
	 * @mbg.generated
	 */
	private Integer companyCategory1;
	/**
	 * Database Column Remarks: ビジネスカテゴリ2:マスタテーブルFK This field was generated by MyBatis Generator. This field corresponds to the database column company.company_category2
	 * @mbg.generated
	 */
	private Integer companyCategory2;
	/**
	 * Database Column Remarks: ビジネスカテゴリ3:マスタテーブルFK This field was generated by MyBatis Generator. This field corresponds to the database column company.company_category3
	 * @mbg.generated
	 */
	private Integer companyCategory3;
	/**
	 * Database Column Remarks: 使用中プラン This field was generated by MyBatis Generator. This field corresponds to the database column company.company_plan_id
	 * @mbg.generated
	 */
	private Integer companyPlanId;
	/**
	 * Database Column Remarks: プラン自動更新区分:0:自動更新しない 1:自動更新する This field was generated by MyBatis Generator. This field corresponds to the database column company.plan_renewal_category
	 * @mbg.generated
	 */
	private String planRenewalCategory;
	/**
	 * Database Column Remarks: ロゴ面像パス This field was generated by MyBatis Generator. This field corresponds to the database column company.logo_path
	 * @mbg.generated
	 */
	private String logoPath;
	/**
	 * Database Column Remarks: カバ写真表示するか:0:表示しない 1:表示する This field was generated by MyBatis Generator. This field corresponds to the database column company.is_displayed_cover_image
	 * @mbg.generated
	 */
	private String isDisplayedCoverImage;
	/**
	 * Database Column Remarks: 削除フラグ This field was generated by MyBatis Generator. This field corresponds to the database column company.delete_flag
	 * @mbg.generated
	 */
	private String deleteFlag;
	/**
	 * Database Column Remarks: 作成者 This field was generated by MyBatis Generator. This field corresponds to the database column company.create_user
	 * @mbg.generated
	 */
	private String createUser;
	/**
	 * Database Column Remarks: 作成日時:yyyy/MM/dd HH:mm:ss This field was generated by MyBatis Generator. This field corresponds to the database column company.create_datetime
	 * @mbg.generated
	 */
	private Date createDatetime;
	/**
	 * Database Column Remarks: 最終更新者 This field was generated by MyBatis Generator. This field corresponds to the database column company.update_user
	 * @mbg.generated
	 */
	private String updateUser;
	/**
	 * Database Column Remarks: 最終更新日時:yyyy/MM/dd HH:mm:ss This field was generated by MyBatis Generator. This field corresponds to the database column company.update_datetime
	 * @mbg.generated
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.id
	 * @return  the value of company.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.id
	 * @param id  the value for company.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.corporate_name
	 * @return  the value of company.corporate_name
	 * @mbg.generated
	 */
	public String getCorporateName() {
		return corporateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.corporate_name
	 * @param corporateName  the value for company.corporate_name
	 * @mbg.generated
	 */
	public void setCorporateName(String corporateName) {
		this.corporateName = corporateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.corporate_name_kana
	 * @return  the value of company.corporate_name_kana
	 * @mbg.generated
	 */
	public String getCorporateNameKana() {
		return corporateNameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.corporate_name_kana
	 * @param corporateNameKana  the value for company.corporate_name_kana
	 * @mbg.generated
	 */
	public void setCorporateNameKana(String corporateNameKana) {
		this.corporateNameKana = corporateNameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.representative_name
	 * @return  the value of company.representative_name
	 * @mbg.generated
	 */
	public String getRepresentativeName() {
		return representativeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.representative_name
	 * @param representativeName  the value for company.representative_name
	 * @mbg.generated
	 */
	public void setRepresentativeName(String representativeName) {
		this.representativeName = representativeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.representative_position
	 * @return  the value of company.representative_position
	 * @mbg.generated
	 */
	public String getRepresentativePosition() {
		return representativePosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.representative_position
	 * @param representativePosition  the value for company.representative_position
	 * @mbg.generated
	 */
	public void setRepresentativePosition(String representativePosition) {
		this.representativePosition = representativePosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.establishment_date
	 * @return  the value of company.establishment_date
	 * @mbg.generated
	 */
	public Date getEstablishmentDate() {
		return establishmentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.establishment_date
	 * @param establishmentDate  the value for company.establishment_date
	 * @mbg.generated
	 */
	public void setEstablishmentDate(Date establishmentDate) {
		this.establishmentDate = establishmentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.address1
	 * @return  the value of company.address1
	 * @mbg.generated
	 */
	public String getAddress1() {
		return address1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.address1
	 * @param address1  the value for company.address1
	 * @mbg.generated
	 */
	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.address2
	 * @return  the value of company.address2
	 * @mbg.generated
	 */
	public String getAddress2() {
		return address2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.address2
	 * @param address2  the value for company.address2
	 * @mbg.generated
	 */
	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.address3
	 * @return  the value of company.address3
	 * @mbg.generated
	 */
	public String getAddress3() {
		return address3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.address3
	 * @param address3  the value for company.address3
	 * @mbg.generated
	 */
	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.representative_phone_no
	 * @return  the value of company.representative_phone_no
	 * @mbg.generated
	 */
	public String getRepresentativePhoneNo() {
		return representativePhoneNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.representative_phone_no
	 * @param representativePhoneNo  the value for company.representative_phone_no
	 * @mbg.generated
	 */
	public void setRepresentativePhoneNo(String representativePhoneNo) {
		this.representativePhoneNo = representativePhoneNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.listing_category
	 * @return  the value of company.listing_category
	 * @mbg.generated
	 */
	public String getListingCategory() {
		return listingCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.listing_category
	 * @param listingCategory  the value for company.listing_category
	 * @mbg.generated
	 */
	public void setListingCategory(String listingCategory) {
		this.listingCategory = listingCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.security_code
	 * @return  the value of company.security_code
	 * @mbg.generated
	 */
	public String getSecurityCode() {
		return securityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.security_code
	 * @param securityCode  the value for company.security_code
	 * @mbg.generated
	 */
	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.capital_amount
	 * @return  the value of company.capital_amount
	 * @mbg.generated
	 */
	public String getCapitalAmount() {
		return capitalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.capital_amount
	 * @param capitalAmount  the value for company.capital_amount
	 * @mbg.generated
	 */
	public void setCapitalAmount(String capitalAmount) {
		this.capitalAmount = capitalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.num_of_employees
	 * @return  the value of company.num_of_employees
	 * @mbg.generated
	 */
	public String getNumOfEmployees() {
		return numOfEmployees;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.num_of_employees
	 * @param numOfEmployees  the value for company.num_of_employees
	 * @mbg.generated
	 */
	public void setNumOfEmployees(String numOfEmployees) {
		this.numOfEmployees = numOfEmployees;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.site_url
	 * @return  the value of company.site_url
	 * @mbg.generated
	 */
	public String getSiteUrl() {
		return siteUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.site_url
	 * @param siteUrl  the value for company.site_url
	 * @mbg.generated
	 */
	public void setSiteUrl(String siteUrl) {
		this.siteUrl = siteUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.industry_category
	 * @return  the value of company.industry_category
	 * @mbg.generated
	 */
	public Integer getIndustryCategory() {
		return industryCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.industry_category
	 * @param industryCategory  the value for company.industry_category
	 * @mbg.generated
	 */
	public void setIndustryCategory(Integer industryCategory) {
		this.industryCategory = industryCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.company_category1
	 * @return  the value of company.company_category1
	 * @mbg.generated
	 */
	public Integer getCompanyCategory1() {
		return companyCategory1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.company_category1
	 * @param companyCategory1  the value for company.company_category1
	 * @mbg.generated
	 */
	public void setCompanyCategory1(Integer companyCategory1) {
		this.companyCategory1 = companyCategory1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.company_category2
	 * @return  the value of company.company_category2
	 * @mbg.generated
	 */
	public Integer getCompanyCategory2() {
		return companyCategory2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.company_category2
	 * @param companyCategory2  the value for company.company_category2
	 * @mbg.generated
	 */
	public void setCompanyCategory2(Integer companyCategory2) {
		this.companyCategory2 = companyCategory2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.company_category3
	 * @return  the value of company.company_category3
	 * @mbg.generated
	 */
	public Integer getCompanyCategory3() {
		return companyCategory3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.company_category3
	 * @param companyCategory3  the value for company.company_category3
	 * @mbg.generated
	 */
	public void setCompanyCategory3(Integer companyCategory3) {
		this.companyCategory3 = companyCategory3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.company_plan_id
	 * @return  the value of company.company_plan_id
	 * @mbg.generated
	 */
	public Integer getCompanyPlanId() {
		return companyPlanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.company_plan_id
	 * @param companyPlanId  the value for company.company_plan_id
	 * @mbg.generated
	 */
	public void setCompanyPlanId(Integer companyPlanId) {
		this.companyPlanId = companyPlanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.plan_renewal_category
	 * @return  the value of company.plan_renewal_category
	 * @mbg.generated
	 */
	public String getPlanRenewalCategory() {
		return planRenewalCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.plan_renewal_category
	 * @param planRenewalCategory  the value for company.plan_renewal_category
	 * @mbg.generated
	 */
	public void setPlanRenewalCategory(String planRenewalCategory) {
		this.planRenewalCategory = planRenewalCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.logo_path
	 * @return  the value of company.logo_path
	 * @mbg.generated
	 */
	public String getLogoPath() {
		return logoPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.logo_path
	 * @param logoPath  the value for company.logo_path
	 * @mbg.generated
	 */
	public void setLogoPath(String logoPath) {
		this.logoPath = logoPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.is_displayed_cover_image
	 * @return  the value of company.is_displayed_cover_image
	 * @mbg.generated
	 */
	public String getIsDisplayedCoverImage() {
		return isDisplayedCoverImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.is_displayed_cover_image
	 * @param isDisplayedCoverImage  the value for company.is_displayed_cover_image
	 * @mbg.generated
	 */
	public void setIsDisplayedCoverImage(String isDisplayedCoverImage) {
		this.isDisplayedCoverImage = isDisplayedCoverImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.delete_flag
	 * @return  the value of company.delete_flag
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.delete_flag
	 * @param deleteFlag  the value for company.delete_flag
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.create_user
	 * @return  the value of company.create_user
	 * @mbg.generated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.create_user
	 * @param createUser  the value for company.create_user
	 * @mbg.generated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.create_datetime
	 * @return  the value of company.create_datetime
	 * @mbg.generated
	 */
	public Date getCreateDatetime() {
		return createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.create_datetime
	 * @param createDatetime  the value for company.create_datetime
	 * @mbg.generated
	 */
	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.update_user
	 * @return  the value of company.update_user
	 * @mbg.generated
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.update_user
	 * @param updateUser  the value for company.update_user
	 * @mbg.generated
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.update_datetime
	 * @return  the value of company.update_datetime
	 * @mbg.generated
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.update_datetime
	 * @param updateDatetime  the value for company.update_datetime
	 * @mbg.generated
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", corporateName=").append(corporateName);
		sb.append(", corporateNameKana=").append(corporateNameKana);
		sb.append(", representativeName=").append(representativeName);
		sb.append(", representativePosition=").append(representativePosition);
		sb.append(", establishmentDate=").append(establishmentDate);
		sb.append(", address1=").append(address1);
		sb.append(", address2=").append(address2);
		sb.append(", address3=").append(address3);
		sb.append(", representativePhoneNo=").append(representativePhoneNo);
		sb.append(", listingCategory=").append(listingCategory);
		sb.append(", securityCode=").append(securityCode);
		sb.append(", capitalAmount=").append(capitalAmount);
		sb.append(", numOfEmployees=").append(numOfEmployees);
		sb.append(", siteUrl=").append(siteUrl);
		sb.append(", industryCategory=").append(industryCategory);
		sb.append(", companyCategory1=").append(companyCategory1);
		sb.append(", companyCategory2=").append(companyCategory2);
		sb.append(", companyCategory3=").append(companyCategory3);
		sb.append(", companyPlanId=").append(companyPlanId);
		sb.append(", planRenewalCategory=").append(planRenewalCategory);
		sb.append(", logoPath=").append(logoPath);
		sb.append(", isDisplayedCoverImage=").append(isDisplayedCoverImage);
		sb.append(", deleteFlag=").append(deleteFlag);
		sb.append(", createUser=").append(createUser);
		sb.append(", createDatetime=").append(createDatetime);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updateDatetime=").append(updateDatetime);
		sb.append("]");
		return sb.toString();
	}
}