package com.jp.sense.pr.model.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table company_category
 */
public class CompanyCategoryKey {
    /**
     * Database Column Remarks:
     *   企業ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_category.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     * Database Column Remarks:
     *   設定カテゴリID:企業カテゴリ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_category.comp_cate_id
     *
     * @mbg.generated
     */
    private Integer compCateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_category.company_id
     *
     * @return the value of company_category.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_category.company_id
     *
     * @param companyId the value for company_category.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_category.comp_cate_id
     *
     * @return the value of company_category.comp_cate_id
     *
     * @mbg.generated
     */
    public Integer getCompCateId() {
        return compCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_category.comp_cate_id
     *
     * @param compCateId the value for company_category.comp_cate_id
     *
     * @mbg.generated
     */
    public void setCompCateId(Integer compCateId) {
        this.compCateId = compCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", companyId=").append(companyId);
        sb.append(", compCateId=").append(compCateId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CompanyCategoryKey other = (CompanyCategoryKey) that;
        return (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getCompCateId() == null ? other.getCompCateId() == null : this.getCompCateId().equals(other.getCompCateId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getCompCateId() == null) ? 0 : getCompCateId().hashCode());
        return result;
    }
}