package com.jp.sense.pr.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table corporateContract_list
 */
public class CorporatecontractList extends CorporatecontractListKey {

	/**
	 * Database Column Remarks: ステータス:1.請求済み,2.未請求,3.請求失敗 This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.STATUS
	 * @mbg.generated
	 */
	private String status;
	/**
	 * Database Column Remarks: 企業名 This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.COMPANYNAME
	 * @mbg.generated
	 */
	private String companyname;
	/**
	 * Database Column Remarks: プラン名称 This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.PLAN_NAME
	 * @mbg.generated
	 */
	private String planName;
	/**
	 * Database Column Remarks: プランサブタイトル This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.PLAN_SUB_TITLE
	 * @mbg.generated
	 */
	private String planSubTitle;
	/**
	 * Database Column Remarks: サービス内容 This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.SERVICE
	 * @mbg.generated
	 */
	private String service;
	/**
	 * Database Column Remarks: サービス単位:1.回 2.月 3.年 This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.SERVICE_UNIT
	 * @mbg.generated
	 */
	private String serviceUnit;
	/**
	 * Database Column Remarks: 配信回数 This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.DELIVER_COUNT
	 * @mbg.generated
	 */
	private Integer deliverCount;
	/**
	 * Database Column Remarks: 配信回数無制限フラグ This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.UNLIMITED_DELIVER_FLAG
	 * @mbg.generated
	 */
	private String unlimitedDeliverFlag;
	/**
	 * Database Column Remarks: 購買内容 This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.PURCHASING_CONTENT
	 * @mbg.generated
	 */
	private String purchasingContent;
	/**
	 * Database Column Remarks: 請求番号 This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.PAYMENT_NUMBER
	 * @mbg.generated
	 */
	private String paymentNumber;
	/**
	 * Database Column Remarks: 料金 This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.PLAN_PRICE
	 * @mbg.generated
	 */
	private Integer planPrice;
	/**
	 * Database Column Remarks: 請求月 This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.REQUEST_MONTH
	 * @mbg.generated
	 */
	private String requestMonth;
	/**
	 * Database Column Remarks: 契約期間:YYYY/MM/DD ~ YYYY/MM/DD This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.CONTRACT_PERIOD
	 * @mbg.generated
	 */
	private String contractPeriod;
	/**
	 * Database Column Remarks: 削除フラグ This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.DELETE_FLAG
	 * @mbg.generated
	 */
	private String deleteFlag;
	/**
	 * Database Column Remarks: 作成者 This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.CREATE_USER
	 * @mbg.generated
	 */
	private String createUser;
	/**
	 * Database Column Remarks: 作成日時:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.CREATE_DATETIME
	 * @mbg.generated
	 */
	private Date createDatetime;
	/**
	 * Database Column Remarks: 最終更新者 This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.UPDATE_USER
	 * @mbg.generated
	 */
	private String updateUser;
	/**
	 * Database Column Remarks: 最終更新日時:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.UPDATE_DATETIME
	 * @mbg.generated
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.STATUS
	 * @return  the value of corporateContract_list.STATUS
	 * @mbg.generated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.STATUS
	 * @param status  the value for corporateContract_list.STATUS
	 * @mbg.generated
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.COMPANYNAME
	 * @return  the value of corporateContract_list.COMPANYNAME
	 * @mbg.generated
	 */
	public String getCompanyname() {
		return companyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.COMPANYNAME
	 * @param companyname  the value for corporateContract_list.COMPANYNAME
	 * @mbg.generated
	 */
	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.PLAN_NAME
	 * @return  the value of corporateContract_list.PLAN_NAME
	 * @mbg.generated
	 */
	public String getPlanName() {
		return planName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.PLAN_NAME
	 * @param planName  the value for corporateContract_list.PLAN_NAME
	 * @mbg.generated
	 */
	public void setPlanName(String planName) {
		this.planName = planName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.PLAN_SUB_TITLE
	 * @return  the value of corporateContract_list.PLAN_SUB_TITLE
	 * @mbg.generated
	 */
	public String getPlanSubTitle() {
		return planSubTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.PLAN_SUB_TITLE
	 * @param planSubTitle  the value for corporateContract_list.PLAN_SUB_TITLE
	 * @mbg.generated
	 */
	public void setPlanSubTitle(String planSubTitle) {
		this.planSubTitle = planSubTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.SERVICE
	 * @return  the value of corporateContract_list.SERVICE
	 * @mbg.generated
	 */
	public String getService() {
		return service;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.SERVICE
	 * @param service  the value for corporateContract_list.SERVICE
	 * @mbg.generated
	 */
	public void setService(String service) {
		this.service = service;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.SERVICE_UNIT
	 * @return  the value of corporateContract_list.SERVICE_UNIT
	 * @mbg.generated
	 */
	public String getServiceUnit() {
		return serviceUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.SERVICE_UNIT
	 * @param serviceUnit  the value for corporateContract_list.SERVICE_UNIT
	 * @mbg.generated
	 */
	public void setServiceUnit(String serviceUnit) {
		this.serviceUnit = serviceUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.DELIVER_COUNT
	 * @return  the value of corporateContract_list.DELIVER_COUNT
	 * @mbg.generated
	 */
	public Integer getDeliverCount() {
		return deliverCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.DELIVER_COUNT
	 * @param deliverCount  the value for corporateContract_list.DELIVER_COUNT
	 * @mbg.generated
	 */
	public void setDeliverCount(Integer deliverCount) {
		this.deliverCount = deliverCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.UNLIMITED_DELIVER_FLAG
	 * @return  the value of corporateContract_list.UNLIMITED_DELIVER_FLAG
	 * @mbg.generated
	 */
	public String getUnlimitedDeliverFlag() {
		return unlimitedDeliverFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.UNLIMITED_DELIVER_FLAG
	 * @param unlimitedDeliverFlag  the value for corporateContract_list.UNLIMITED_DELIVER_FLAG
	 * @mbg.generated
	 */
	public void setUnlimitedDeliverFlag(String unlimitedDeliverFlag) {
		this.unlimitedDeliverFlag = unlimitedDeliverFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.PURCHASING_CONTENT
	 * @return  the value of corporateContract_list.PURCHASING_CONTENT
	 * @mbg.generated
	 */
	public String getPurchasingContent() {
		return purchasingContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.PURCHASING_CONTENT
	 * @param purchasingContent  the value for corporateContract_list.PURCHASING_CONTENT
	 * @mbg.generated
	 */
	public void setPurchasingContent(String purchasingContent) {
		this.purchasingContent = purchasingContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.PAYMENT_NUMBER
	 * @return  the value of corporateContract_list.PAYMENT_NUMBER
	 * @mbg.generated
	 */
	public String getPaymentNumber() {
		return paymentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.PAYMENT_NUMBER
	 * @param paymentNumber  the value for corporateContract_list.PAYMENT_NUMBER
	 * @mbg.generated
	 */
	public void setPaymentNumber(String paymentNumber) {
		this.paymentNumber = paymentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.PLAN_PRICE
	 * @return  the value of corporateContract_list.PLAN_PRICE
	 * @mbg.generated
	 */
	public Integer getPlanPrice() {
		return planPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.PLAN_PRICE
	 * @param planPrice  the value for corporateContract_list.PLAN_PRICE
	 * @mbg.generated
	 */
	public void setPlanPrice(Integer planPrice) {
		this.planPrice = planPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.REQUEST_MONTH
	 * @return  the value of corporateContract_list.REQUEST_MONTH
	 * @mbg.generated
	 */
	public String getRequestMonth() {
		return requestMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.REQUEST_MONTH
	 * @param requestMonth  the value for corporateContract_list.REQUEST_MONTH
	 * @mbg.generated
	 */
	public void setRequestMonth(String requestMonth) {
		this.requestMonth = requestMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.CONTRACT_PERIOD
	 * @return  the value of corporateContract_list.CONTRACT_PERIOD
	 * @mbg.generated
	 */
	public String getContractPeriod() {
		return contractPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.CONTRACT_PERIOD
	 * @param contractPeriod  the value for corporateContract_list.CONTRACT_PERIOD
	 * @mbg.generated
	 */
	public void setContractPeriod(String contractPeriod) {
		this.contractPeriod = contractPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.DELETE_FLAG
	 * @return  the value of corporateContract_list.DELETE_FLAG
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.DELETE_FLAG
	 * @param deleteFlag  the value for corporateContract_list.DELETE_FLAG
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.CREATE_USER
	 * @return  the value of corporateContract_list.CREATE_USER
	 * @mbg.generated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.CREATE_USER
	 * @param createUser  the value for corporateContract_list.CREATE_USER
	 * @mbg.generated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.CREATE_DATETIME
	 * @return  the value of corporateContract_list.CREATE_DATETIME
	 * @mbg.generated
	 */
	public Date getCreateDatetime() {
		return createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.CREATE_DATETIME
	 * @param createDatetime  the value for corporateContract_list.CREATE_DATETIME
	 * @mbg.generated
	 */
	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.UPDATE_USER
	 * @return  the value of corporateContract_list.UPDATE_USER
	 * @mbg.generated
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.UPDATE_USER
	 * @param updateUser  the value for corporateContract_list.UPDATE_USER
	 * @mbg.generated
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.UPDATE_DATETIME
	 * @return  the value of corporateContract_list.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.UPDATE_DATETIME
	 * @param updateDatetime  the value for corporateContract_list.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table corporateContract_list
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", status=").append(status);
		sb.append(", companyname=").append(companyname);
		sb.append(", planName=").append(planName);
		sb.append(", planSubTitle=").append(planSubTitle);
		sb.append(", service=").append(service);
		sb.append(", serviceUnit=").append(serviceUnit);
		sb.append(", deliverCount=").append(deliverCount);
		sb.append(", unlimitedDeliverFlag=").append(unlimitedDeliverFlag);
		sb.append(", purchasingContent=").append(purchasingContent);
		sb.append(", paymentNumber=").append(paymentNumber);
		sb.append(", planPrice=").append(planPrice);
		sb.append(", requestMonth=").append(requestMonth);
		sb.append(", contractPeriod=").append(contractPeriod);
		sb.append(", deleteFlag=").append(deleteFlag);
		sb.append(", createUser=").append(createUser);
		sb.append(", createDatetime=").append(createDatetime);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updateDatetime=").append(updateDatetime);
		sb.append("]");
		return sb.toString();
	}
}