package com.jp.sense.pr.model.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table corporateContract_list
 */
public class CorporatecontractListKey {

	/**
	 * Database Column Remarks: ID This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 企業ID This field was generated by MyBatis Generator. This field corresponds to the database column corporateContract_list.COMPANYID
	 * @mbg.generated
	 */
	private Integer companyid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.ID
	 * @return  the value of corporateContract_list.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.ID
	 * @param id  the value for corporateContract_list.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column corporateContract_list.COMPANYID
	 * @return  the value of corporateContract_list.COMPANYID
	 * @mbg.generated
	 */
	public Integer getCompanyid() {
		return companyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column corporateContract_list.COMPANYID
	 * @param companyid  the value for corporateContract_list.COMPANYID
	 * @mbg.generated
	 */
	public void setCompanyid(Integer companyid) {
		this.companyid = companyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table corporateContract_list
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", companyid=").append(companyid);
		sb.append("]");
		return sb.toString();
	}
}