package com.jp.sense.pr.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table media_user
 */
public class MediaUser {

	/**
	 * Database Column Remarks: メディアユーザーID This field was generated by MyBatis Generator. This field corresponds to the database column media_user.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: アカウント種別:0:個人 1:メディア This field was generated by MyBatis Generator. This field corresponds to the database column media_user.ACCOUNT_TYPE
	 * @mbg.generated
	 */
	private String accountType;
	/**
	 * Database Column Remarks: メールアドレス This field was generated by MyBatis Generator. This field corresponds to the database column media_user.EMAIL
	 * @mbg.generated
	 */
	private String email;
	/**
	 * Database Column Remarks: パスワード This field was generated by MyBatis Generator. This field corresponds to the database column media_user.PASSWORD
	 * @mbg.generated
	 */
	private String password;
	/**
	 * Database Column Remarks: 氏名 This field was generated by MyBatis Generator. This field corresponds to the database column media_user.NAME
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 媒体社名／部署:フォーマット：媒体社名/所属部署 This field was generated by MyBatis Generator. This field corresponds to the database column media_user.MEDIUM_COMPANY_NAME
	 * @mbg.generated
	 */
	private String mediumCompanyName;
	/**
	 * Database Column Remarks: 媒体種類:マスタテーブルFK This field was generated by MyBatis Generator. This field corresponds to the database column media_user.MEDIUM_TYPE
	 * @mbg.generated
	 */
	private Integer mediumType;
	/**
	 * Database Column Remarks: 媒体名 This field was generated by MyBatis Generator. This field corresponds to the database column media_user.MEDIUM_NAME
	 * @mbg.generated
	 */
	private String mediumName;
	/**
	 * Database Column Remarks: 追加媒体情報 This field was generated by MyBatis Generator. This field corresponds to the database column media_user.MEDIUM_NAME_EXTRA
	 * @mbg.generated
	 */
	private String mediumNameExtra;
	/**
	 * Database Column Remarks: 本社所在地（郵便番号） This field was generated by MyBatis Generator. This field corresponds to the database column media_user.ADDRESS1
	 * @mbg.generated
	 */
	private String address1;
	/**
	 * Database Column Remarks: 本社所在地（都道府県市区町村番地） This field was generated by MyBatis Generator. This field corresponds to the database column media_user.ADDRESS2
	 * @mbg.generated
	 */
	private String address2;
	/**
	 * Database Column Remarks: 本社所在地（建物・階数） This field was generated by MyBatis Generator. This field corresponds to the database column media_user.ADDRESS3
	 * @mbg.generated
	 */
	private String address3;
	/**
	 * Database Column Remarks: 電話番号 This field was generated by MyBatis Generator. This field corresponds to the database column media_user.PHONE_NO
	 * @mbg.generated
	 */
	private String phoneNo;
	/**
	 * Database Column Remarks: FAX This field was generated by MyBatis Generator. This field corresponds to the database column media_user.FAX
	 * @mbg.generated
	 */
	private String fax;
	/**
	 * Database Column Remarks: メール受信設定:0:OFF 1:ON This field was generated by MyBatis Generator. This field corresponds to the database column media_user.RECEIVE_CONFIG_MAIL
	 * @mbg.generated
	 */
	private String receiveConfigMail;
	/**
	 * Database Column Remarks: 削除フラグ This field was generated by MyBatis Generator. This field corresponds to the database column media_user.DELETE_FLAG
	 * @mbg.generated
	 */
	private String deleteFlag;
	/**
	 * Database Column Remarks: 作成者 This field was generated by MyBatis Generator. This field corresponds to the database column media_user.CREATE_USER
	 * @mbg.generated
	 */
	private String createUser;
	/**
	 * Database Column Remarks: 作成日時:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column media_user.CREATE_DATETIME
	 * @mbg.generated
	 */
	private Date createDatetime;
	/**
	 * Database Column Remarks: 最終更新者 This field was generated by MyBatis Generator. This field corresponds to the database column media_user.UPDATE_USER
	 * @mbg.generated
	 */
	private String updateUser;
	/**
	 * Database Column Remarks: 最終更新日時:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column media_user.UPDATE_DATETIME
	 * @mbg.generated
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.ID
	 * @return  the value of media_user.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.ID
	 * @param id  the value for media_user.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.ACCOUNT_TYPE
	 * @return  the value of media_user.ACCOUNT_TYPE
	 * @mbg.generated
	 */
	public String getAccountType() {
		return accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.ACCOUNT_TYPE
	 * @param accountType  the value for media_user.ACCOUNT_TYPE
	 * @mbg.generated
	 */
	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.EMAIL
	 * @return  the value of media_user.EMAIL
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.EMAIL
	 * @param email  the value for media_user.EMAIL
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.PASSWORD
	 * @return  the value of media_user.PASSWORD
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.PASSWORD
	 * @param password  the value for media_user.PASSWORD
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.NAME
	 * @return  the value of media_user.NAME
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.NAME
	 * @param name  the value for media_user.NAME
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.MEDIUM_COMPANY_NAME
	 * @return  the value of media_user.MEDIUM_COMPANY_NAME
	 * @mbg.generated
	 */
	public String getMediumCompanyName() {
		return mediumCompanyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.MEDIUM_COMPANY_NAME
	 * @param mediumCompanyName  the value for media_user.MEDIUM_COMPANY_NAME
	 * @mbg.generated
	 */
	public void setMediumCompanyName(String mediumCompanyName) {
		this.mediumCompanyName = mediumCompanyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.MEDIUM_TYPE
	 * @return  the value of media_user.MEDIUM_TYPE
	 * @mbg.generated
	 */
	public Integer getMediumType() {
		return mediumType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.MEDIUM_TYPE
	 * @param mediumType  the value for media_user.MEDIUM_TYPE
	 * @mbg.generated
	 */
	public void setMediumType(Integer mediumType) {
		this.mediumType = mediumType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.MEDIUM_NAME
	 * @return  the value of media_user.MEDIUM_NAME
	 * @mbg.generated
	 */
	public String getMediumName() {
		return mediumName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.MEDIUM_NAME
	 * @param mediumName  the value for media_user.MEDIUM_NAME
	 * @mbg.generated
	 */
	public void setMediumName(String mediumName) {
		this.mediumName = mediumName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.MEDIUM_NAME_EXTRA
	 * @return  the value of media_user.MEDIUM_NAME_EXTRA
	 * @mbg.generated
	 */
	public String getMediumNameExtra() {
		return mediumNameExtra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.MEDIUM_NAME_EXTRA
	 * @param mediumNameExtra  the value for media_user.MEDIUM_NAME_EXTRA
	 * @mbg.generated
	 */
	public void setMediumNameExtra(String mediumNameExtra) {
		this.mediumNameExtra = mediumNameExtra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.ADDRESS1
	 * @return  the value of media_user.ADDRESS1
	 * @mbg.generated
	 */
	public String getAddress1() {
		return address1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.ADDRESS1
	 * @param address1  the value for media_user.ADDRESS1
	 * @mbg.generated
	 */
	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.ADDRESS2
	 * @return  the value of media_user.ADDRESS2
	 * @mbg.generated
	 */
	public String getAddress2() {
		return address2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.ADDRESS2
	 * @param address2  the value for media_user.ADDRESS2
	 * @mbg.generated
	 */
	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.ADDRESS3
	 * @return  the value of media_user.ADDRESS3
	 * @mbg.generated
	 */
	public String getAddress3() {
		return address3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.ADDRESS3
	 * @param address3  the value for media_user.ADDRESS3
	 * @mbg.generated
	 */
	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.PHONE_NO
	 * @return  the value of media_user.PHONE_NO
	 * @mbg.generated
	 */
	public String getPhoneNo() {
		return phoneNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.PHONE_NO
	 * @param phoneNo  the value for media_user.PHONE_NO
	 * @mbg.generated
	 */
	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.FAX
	 * @return  the value of media_user.FAX
	 * @mbg.generated
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.FAX
	 * @param fax  the value for media_user.FAX
	 * @mbg.generated
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.RECEIVE_CONFIG_MAIL
	 * @return  the value of media_user.RECEIVE_CONFIG_MAIL
	 * @mbg.generated
	 */
	public String getReceiveConfigMail() {
		return receiveConfigMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.RECEIVE_CONFIG_MAIL
	 * @param receiveConfigMail  the value for media_user.RECEIVE_CONFIG_MAIL
	 * @mbg.generated
	 */
	public void setReceiveConfigMail(String receiveConfigMail) {
		this.receiveConfigMail = receiveConfigMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.DELETE_FLAG
	 * @return  the value of media_user.DELETE_FLAG
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.DELETE_FLAG
	 * @param deleteFlag  the value for media_user.DELETE_FLAG
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.CREATE_USER
	 * @return  the value of media_user.CREATE_USER
	 * @mbg.generated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.CREATE_USER
	 * @param createUser  the value for media_user.CREATE_USER
	 * @mbg.generated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.CREATE_DATETIME
	 * @return  the value of media_user.CREATE_DATETIME
	 * @mbg.generated
	 */
	public Date getCreateDatetime() {
		return createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.CREATE_DATETIME
	 * @param createDatetime  the value for media_user.CREATE_DATETIME
	 * @mbg.generated
	 */
	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.UPDATE_USER
	 * @return  the value of media_user.UPDATE_USER
	 * @mbg.generated
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.UPDATE_USER
	 * @param updateUser  the value for media_user.UPDATE_USER
	 * @mbg.generated
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_user.UPDATE_DATETIME
	 * @return  the value of media_user.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_user.UPDATE_DATETIME
	 * @param updateDatetime  the value for media_user.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_user
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", accountType=").append(accountType);
		sb.append(", email=").append(email);
		sb.append(", password=").append(password);
		sb.append(", name=").append(name);
		sb.append(", mediumCompanyName=").append(mediumCompanyName);
		sb.append(", mediumType=").append(mediumType);
		sb.append(", mediumName=").append(mediumName);
		sb.append(", mediumNameExtra=").append(mediumNameExtra);
		sb.append(", address1=").append(address1);
		sb.append(", address2=").append(address2);
		sb.append(", address3=").append(address3);
		sb.append(", phoneNo=").append(phoneNo);
		sb.append(", fax=").append(fax);
		sb.append(", receiveConfigMail=").append(receiveConfigMail);
		sb.append(", deleteFlag=").append(deleteFlag);
		sb.append(", createUser=").append(createUser);
		sb.append(", createDatetime=").append(createDatetime);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updateDatetime=").append(updateDatetime);
		sb.append("]");
		return sb.toString();
	}
}