package com.jp.sense.pr.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table notification_manage
 */
public class NotificationManage {

	/**
	 * Database Column Remarks: お知らせID This field was generated by MyBatis Generator. This field corresponds to the database column notification_manage.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: お知らせタイトル This field was generated by MyBatis Generator. This field corresponds to the database column notification_manage.NOTIFICATION_TITLE
	 * @mbg.generated
	 */
	private String notificationTitle;
	/**
	 * Database Column Remarks: お知らせリンク This field was generated by MyBatis Generator. This field corresponds to the database column notification_manage.NOTIFICATION_URL
	 * @mbg.generated
	 */
	private String notificationUrl;
	/**
	 * Database Column Remarks: 公開フラグ:0: 公開しない　1: 公開する This field was generated by MyBatis Generator. This field corresponds to the database column notification_manage.RELEASE_FLAG
	 * @mbg.generated
	 */
	private String releaseFlag;
	/**
	 * Database Column Remarks: 削除フラグ:0: 削除しない　1: 削除する This field was generated by MyBatis Generator. This field corresponds to the database column notification_manage.DELETE_FLAG
	 * @mbg.generated
	 */
	private String deleteFlag;
	/**
	 * Database Column Remarks: 作成者 This field was generated by MyBatis Generator. This field corresponds to the database column notification_manage.CREATE_USER
	 * @mbg.generated
	 */
	private String createUser;
	/**
	 * Database Column Remarks: 作成日時:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column notification_manage.CREATE_DATETIME
	 * @mbg.generated
	 */
	private Date createDatetime;
	/**
	 * Database Column Remarks: 最終更新者 This field was generated by MyBatis Generator. This field corresponds to the database column notification_manage.UPDATE_USER
	 * @mbg.generated
	 */
	private String updateUser;
	/**
	 * Database Column Remarks: 最終更新日時:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column notification_manage.UPDATE_DATETIME
	 * @mbg.generated
	 */
	private Date updateDatetime;
	/**
	 * Database Column Remarks: お知らせ本文 This field was generated by MyBatis Generator. This field corresponds to the database column notification_manage.NOTIFICATION_TEXT
	 * @mbg.generated
	 */
	private String notificationText;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_manage.ID
	 * @return  the value of notification_manage.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_manage.ID
	 * @param id  the value for notification_manage.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_manage.NOTIFICATION_TITLE
	 * @return  the value of notification_manage.NOTIFICATION_TITLE
	 * @mbg.generated
	 */
	public String getNotificationTitle() {
		return notificationTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_manage.NOTIFICATION_TITLE
	 * @param notificationTitle  the value for notification_manage.NOTIFICATION_TITLE
	 * @mbg.generated
	 */
	public void setNotificationTitle(String notificationTitle) {
		this.notificationTitle = notificationTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_manage.NOTIFICATION_URL
	 * @return  the value of notification_manage.NOTIFICATION_URL
	 * @mbg.generated
	 */
	public String getNotificationUrl() {
		return notificationUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_manage.NOTIFICATION_URL
	 * @param notificationUrl  the value for notification_manage.NOTIFICATION_URL
	 * @mbg.generated
	 */
	public void setNotificationUrl(String notificationUrl) {
		this.notificationUrl = notificationUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_manage.RELEASE_FLAG
	 * @return  the value of notification_manage.RELEASE_FLAG
	 * @mbg.generated
	 */
	public String getReleaseFlag() {
		return releaseFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_manage.RELEASE_FLAG
	 * @param releaseFlag  the value for notification_manage.RELEASE_FLAG
	 * @mbg.generated
	 */
	public void setReleaseFlag(String releaseFlag) {
		this.releaseFlag = releaseFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_manage.DELETE_FLAG
	 * @return  the value of notification_manage.DELETE_FLAG
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_manage.DELETE_FLAG
	 * @param deleteFlag  the value for notification_manage.DELETE_FLAG
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_manage.CREATE_USER
	 * @return  the value of notification_manage.CREATE_USER
	 * @mbg.generated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_manage.CREATE_USER
	 * @param createUser  the value for notification_manage.CREATE_USER
	 * @mbg.generated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_manage.CREATE_DATETIME
	 * @return  the value of notification_manage.CREATE_DATETIME
	 * @mbg.generated
	 */
	public Date getCreateDatetime() {
		return createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_manage.CREATE_DATETIME
	 * @param createDatetime  the value for notification_manage.CREATE_DATETIME
	 * @mbg.generated
	 */
	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_manage.UPDATE_USER
	 * @return  the value of notification_manage.UPDATE_USER
	 * @mbg.generated
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_manage.UPDATE_USER
	 * @param updateUser  the value for notification_manage.UPDATE_USER
	 * @mbg.generated
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_manage.UPDATE_DATETIME
	 * @return  the value of notification_manage.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_manage.UPDATE_DATETIME
	 * @param updateDatetime  the value for notification_manage.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_manage.NOTIFICATION_TEXT
	 * @return  the value of notification_manage.NOTIFICATION_TEXT
	 * @mbg.generated
	 */
	public String getNotificationText() {
		return notificationText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_manage.NOTIFICATION_TEXT
	 * @param notificationText  the value for notification_manage.NOTIFICATION_TEXT
	 * @mbg.generated
	 */
	public void setNotificationText(String notificationText) {
		this.notificationText = notificationText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notification_manage
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", notificationTitle=").append(notificationTitle);
		sb.append(", notificationUrl=").append(notificationUrl);
		sb.append(", releaseFlag=").append(releaseFlag);
		sb.append(", deleteFlag=").append(deleteFlag);
		sb.append(", createUser=").append(createUser);
		sb.append(", createDatetime=").append(createDatetime);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updateDatetime=").append(updateDatetime);
		sb.append(", notificationText=").append(notificationText);
		sb.append("]");
		return sb.toString();
	}
}