package com.jp.sense.pr.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table operator_info
 */
public class OperatorInfo {

	/**
	 * Database Column Remarks: オペレータ情報ID This field was generated by MyBatis Generator. This field corresponds to the database column operator_info.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: ユーザー名 This field was generated by MyBatis Generator. This field corresponds to the database column operator_info.user_name
	 * @mbg.generated
	 */
	private String userName;
	/**
	 * Database Column Remarks: パスワード This field was generated by MyBatis Generator. This field corresponds to the database column operator_info.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * Database Column Remarks: 氏名 This field was generated by MyBatis Generator. This field corresponds to the database column operator_info.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: Emailアドレス This field was generated by MyBatis Generator. This field corresponds to the database column operator_info.mail_address
	 * @mbg.generated
	 */
	private String mailAddress;
	/**
	 * Database Column Remarks: 電話番号 This field was generated by MyBatis Generator. This field corresponds to the database column operator_info.phone_no
	 * @mbg.generated
	 */
	private String phoneNo;
	/**
	 * Database Column Remarks: 管理者フラグ This field was generated by MyBatis Generator. This field corresponds to the database column operator_info.admin_flag
	 * @mbg.generated
	 */
	private String adminFlag;
	/**
	 * Database Column Remarks: 削除フラグ This field was generated by MyBatis Generator. This field corresponds to the database column operator_info.delete_flag
	 * @mbg.generated
	 */
	private String deleteFlag;
	/**
	 * Database Column Remarks: 作成者 This field was generated by MyBatis Generator. This field corresponds to the database column operator_info.create_user
	 * @mbg.generated
	 */
	private String createUser;
	/**
	 * Database Column Remarks: 作成日時 This field was generated by MyBatis Generator. This field corresponds to the database column operator_info.create_datetime
	 * @mbg.generated
	 */
	private Date createDatetime;
	/**
	 * Database Column Remarks: 最終更新者 This field was generated by MyBatis Generator. This field corresponds to the database column operator_info.update_user
	 * @mbg.generated
	 */
	private String updateUser;
	/**
	 * Database Column Remarks: 最終更新日時 This field was generated by MyBatis Generator. This field corresponds to the database column operator_info.update_datetime
	 * @mbg.generated
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operator_info.id
	 * @return  the value of operator_info.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operator_info.id
	 * @param id  the value for operator_info.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operator_info.user_name
	 * @return  the value of operator_info.user_name
	 * @mbg.generated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operator_info.user_name
	 * @param userName  the value for operator_info.user_name
	 * @mbg.generated
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operator_info.password
	 * @return  the value of operator_info.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operator_info.password
	 * @param password  the value for operator_info.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operator_info.name
	 * @return  the value of operator_info.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operator_info.name
	 * @param name  the value for operator_info.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operator_info.mail_address
	 * @return  the value of operator_info.mail_address
	 * @mbg.generated
	 */
	public String getMailAddress() {
		return mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operator_info.mail_address
	 * @param mailAddress  the value for operator_info.mail_address
	 * @mbg.generated
	 */
	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operator_info.phone_no
	 * @return  the value of operator_info.phone_no
	 * @mbg.generated
	 */
	public String getPhoneNo() {
		return phoneNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operator_info.phone_no
	 * @param phoneNo  the value for operator_info.phone_no
	 * @mbg.generated
	 */
	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operator_info.admin_flag
	 * @return  the value of operator_info.admin_flag
	 * @mbg.generated
	 */
	public String getAdminFlag() {
		return adminFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operator_info.admin_flag
	 * @param adminFlag  the value for operator_info.admin_flag
	 * @mbg.generated
	 */
	public void setAdminFlag(String adminFlag) {
		this.adminFlag = adminFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operator_info.delete_flag
	 * @return  the value of operator_info.delete_flag
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operator_info.delete_flag
	 * @param deleteFlag  the value for operator_info.delete_flag
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operator_info.create_user
	 * @return  the value of operator_info.create_user
	 * @mbg.generated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operator_info.create_user
	 * @param createUser  the value for operator_info.create_user
	 * @mbg.generated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operator_info.create_datetime
	 * @return  the value of operator_info.create_datetime
	 * @mbg.generated
	 */
	public Date getCreateDatetime() {
		return createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operator_info.create_datetime
	 * @param createDatetime  the value for operator_info.create_datetime
	 * @mbg.generated
	 */
	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operator_info.update_user
	 * @return  the value of operator_info.update_user
	 * @mbg.generated
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operator_info.update_user
	 * @param updateUser  the value for operator_info.update_user
	 * @mbg.generated
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operator_info.update_datetime
	 * @return  the value of operator_info.update_datetime
	 * @mbg.generated
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operator_info.update_datetime
	 * @param updateDatetime  the value for operator_info.update_datetime
	 * @mbg.generated
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table operator_info
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", userName=").append(userName);
		sb.append(", password=").append(password);
		sb.append(", name=").append(name);
		sb.append(", mailAddress=").append(mailAddress);
		sb.append(", phoneNo=").append(phoneNo);
		sb.append(", adminFlag=").append(adminFlag);
		sb.append(", deleteFlag=").append(deleteFlag);
		sb.append(", createUser=").append(createUser);
		sb.append(", createDatetime=").append(createDatetime);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updateDatetime=").append(updateDatetime);
		sb.append("]");
		return sb.toString();
	}
}