package com.jp.sense.pr.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table prefectures
 */
public class Prefectures {

	/**
	 * Database Column Remarks: 都道府県ID This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 郵便番号 This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.POST_CODE
	 * @mbg.generated
	 */
	private String postCode;
	/**
	 * Database Column Remarks: 都道府県名カタカナ This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.PREFECTURE_KATAKANA
	 * @mbg.generated
	 */
	private String prefectureKatakana;
	/**
	 * Database Column Remarks: 市区町村名カタカナ This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.CITY_KATAKANA
	 * @mbg.generated
	 */
	private String cityKatakana;
	/**
	 * Database Column Remarks: 町域名カタカナ This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.TOWN_KATAKANA
	 * @mbg.generated
	 */
	private String townKatakana;
	/**
	 * Database Column Remarks: 都道府県名 This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.PREFECTURE
	 * @mbg.generated
	 */
	private String prefecture;
	/**
	 * Database Column Remarks: 市区町村名 This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.CITY
	 * @mbg.generated
	 */
	private String city;
	/**
	 * Database Column Remarks: 町域名 This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.TOWN
	 * @mbg.generated
	 */
	private String town;
	/**
	 * Database Column Remarks: 削除フラグ:0: 削除しない　1: 削除する This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.DELETE_FLAG
	 * @mbg.generated
	 */
	private String deleteFlag;
	/**
	 * Database Column Remarks: 作成者 This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.CREATE_USER
	 * @mbg.generated
	 */
	private String createUser;
	/**
	 * Database Column Remarks: 作成日時 This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.CREATE_DATETIME
	 * @mbg.generated
	 */
	private Date createDatetime;
	/**
	 * Database Column Remarks: 最終更新者 This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.UPDATE_USER
	 * @mbg.generated
	 */
	private String updateUser;
	/**
	 * Database Column Remarks: 最終更新日時 This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.UPDATE_DATETIME
	 * @mbg.generated
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.ID
	 * @return  the value of prefectures.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.ID
	 * @param id  the value for prefectures.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.POST_CODE
	 * @return  the value of prefectures.POST_CODE
	 * @mbg.generated
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.POST_CODE
	 * @param postCode  the value for prefectures.POST_CODE
	 * @mbg.generated
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.PREFECTURE_KATAKANA
	 * @return  the value of prefectures.PREFECTURE_KATAKANA
	 * @mbg.generated
	 */
	public String getPrefectureKatakana() {
		return prefectureKatakana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.PREFECTURE_KATAKANA
	 * @param prefectureKatakana  the value for prefectures.PREFECTURE_KATAKANA
	 * @mbg.generated
	 */
	public void setPrefectureKatakana(String prefectureKatakana) {
		this.prefectureKatakana = prefectureKatakana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.CITY_KATAKANA
	 * @return  the value of prefectures.CITY_KATAKANA
	 * @mbg.generated
	 */
	public String getCityKatakana() {
		return cityKatakana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.CITY_KATAKANA
	 * @param cityKatakana  the value for prefectures.CITY_KATAKANA
	 * @mbg.generated
	 */
	public void setCityKatakana(String cityKatakana) {
		this.cityKatakana = cityKatakana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.TOWN_KATAKANA
	 * @return  the value of prefectures.TOWN_KATAKANA
	 * @mbg.generated
	 */
	public String getTownKatakana() {
		return townKatakana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.TOWN_KATAKANA
	 * @param townKatakana  the value for prefectures.TOWN_KATAKANA
	 * @mbg.generated
	 */
	public void setTownKatakana(String townKatakana) {
		this.townKatakana = townKatakana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.PREFECTURE
	 * @return  the value of prefectures.PREFECTURE
	 * @mbg.generated
	 */
	public String getPrefecture() {
		return prefecture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.PREFECTURE
	 * @param prefecture  the value for prefectures.PREFECTURE
	 * @mbg.generated
	 */
	public void setPrefecture(String prefecture) {
		this.prefecture = prefecture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.CITY
	 * @return  the value of prefectures.CITY
	 * @mbg.generated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.CITY
	 * @param city  the value for prefectures.CITY
	 * @mbg.generated
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.TOWN
	 * @return  the value of prefectures.TOWN
	 * @mbg.generated
	 */
	public String getTown() {
		return town;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.TOWN
	 * @param town  the value for prefectures.TOWN
	 * @mbg.generated
	 */
	public void setTown(String town) {
		this.town = town;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.DELETE_FLAG
	 * @return  the value of prefectures.DELETE_FLAG
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.DELETE_FLAG
	 * @param deleteFlag  the value for prefectures.DELETE_FLAG
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.CREATE_USER
	 * @return  the value of prefectures.CREATE_USER
	 * @mbg.generated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.CREATE_USER
	 * @param createUser  the value for prefectures.CREATE_USER
	 * @mbg.generated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.CREATE_DATETIME
	 * @return  the value of prefectures.CREATE_DATETIME
	 * @mbg.generated
	 */
	public Date getCreateDatetime() {
		return createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.CREATE_DATETIME
	 * @param createDatetime  the value for prefectures.CREATE_DATETIME
	 * @mbg.generated
	 */
	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.UPDATE_USER
	 * @return  the value of prefectures.UPDATE_USER
	 * @mbg.generated
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.UPDATE_USER
	 * @param updateUser  the value for prefectures.UPDATE_USER
	 * @mbg.generated
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.UPDATE_DATETIME
	 * @return  the value of prefectures.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.UPDATE_DATETIME
	 * @param updateDatetime  the value for prefectures.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prefectures
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", postCode=").append(postCode);
		sb.append(", prefectureKatakana=").append(prefectureKatakana);
		sb.append(", cityKatakana=").append(cityKatakana);
		sb.append(", townKatakana=").append(townKatakana);
		sb.append(", prefecture=").append(prefecture);
		sb.append(", city=").append(city);
		sb.append(", town=").append(town);
		sb.append(", deleteFlag=").append(deleteFlag);
		sb.append(", createUser=").append(createUser);
		sb.append(", createDatetime=").append(createDatetime);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updateDatetime=").append(updateDatetime);
		sb.append("]");
		return sb.toString();
	}
}