package com.jp.sense.pr.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table press_release_access_history
 */
public class PressReleaseAccessHistory extends PressReleaseAccessHistoryKey {

	/**
	 * Database Column Remarks: メディアユーザーID This field was generated by MyBatis Generator. This field corresponds to the database column press_release_access_history.MEDIA_USER_ID
	 * @mbg.generated
	 */
	private Integer mediaUserId;
	/**
	 * Database Column Remarks: アクセスIP This field was generated by MyBatis Generator. This field corresponds to the database column press_release_access_history.ACCESS_IP
	 * @mbg.generated
	 */
	private String accessIp;
	/**
	 * Database Column Remarks: アクセス時間:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column press_release_access_history.ACCESS_TIME
	 * @mbg.generated
	 */
	private Date accessTime;
	/**
	 * Database Column Remarks: リーダータイプ This field was generated by MyBatis Generator. This field corresponds to the database column press_release_access_history.READER_TYPE
	 * @mbg.generated
	 */
	private String readerType;
	/**
	 * Database Column Remarks: 削除フラグ This field was generated by MyBatis Generator. This field corresponds to the database column press_release_access_history.DELETE_FLAG
	 * @mbg.generated
	 */
	private String deleteFlag;
	/**
	 * Database Column Remarks: 作成者 This field was generated by MyBatis Generator. This field corresponds to the database column press_release_access_history.CREATE_USER
	 * @mbg.generated
	 */
	private String createUser;
	/**
	 * Database Column Remarks: 作成日時:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column press_release_access_history.CREATE_DATETIME
	 * @mbg.generated
	 */
	private Date createDatetime;
	/**
	 * Database Column Remarks: 最終更新者 This field was generated by MyBatis Generator. This field corresponds to the database column press_release_access_history.UPDATE_USER
	 * @mbg.generated
	 */
	private String updateUser;
	/**
	 * Database Column Remarks: 最終更新日時:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column press_release_access_history.UPDATE_DATETIME
	 * @mbg.generated
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_access_history.MEDIA_USER_ID
	 * @return  the value of press_release_access_history.MEDIA_USER_ID
	 * @mbg.generated
	 */
	public Integer getMediaUserId() {
		return mediaUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_access_history.MEDIA_USER_ID
	 * @param mediaUserId  the value for press_release_access_history.MEDIA_USER_ID
	 * @mbg.generated
	 */
	public void setMediaUserId(Integer mediaUserId) {
		this.mediaUserId = mediaUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_access_history.ACCESS_IP
	 * @return  the value of press_release_access_history.ACCESS_IP
	 * @mbg.generated
	 */
	public String getAccessIp() {
		return accessIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_access_history.ACCESS_IP
	 * @param accessIp  the value for press_release_access_history.ACCESS_IP
	 * @mbg.generated
	 */
	public void setAccessIp(String accessIp) {
		this.accessIp = accessIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_access_history.ACCESS_TIME
	 * @return  the value of press_release_access_history.ACCESS_TIME
	 * @mbg.generated
	 */
	public Date getAccessTime() {
		return accessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_access_history.ACCESS_TIME
	 * @param accessTime  the value for press_release_access_history.ACCESS_TIME
	 * @mbg.generated
	 */
	public void setAccessTime(Date accessTime) {
		this.accessTime = accessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_access_history.READER_TYPE
	 * @return  the value of press_release_access_history.READER_TYPE
	 * @mbg.generated
	 */
	public String getReaderType() {
		return readerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_access_history.READER_TYPE
	 * @param readerType  the value for press_release_access_history.READER_TYPE
	 * @mbg.generated
	 */
	public void setReaderType(String readerType) {
		this.readerType = readerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_access_history.DELETE_FLAG
	 * @return  the value of press_release_access_history.DELETE_FLAG
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_access_history.DELETE_FLAG
	 * @param deleteFlag  the value for press_release_access_history.DELETE_FLAG
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_access_history.CREATE_USER
	 * @return  the value of press_release_access_history.CREATE_USER
	 * @mbg.generated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_access_history.CREATE_USER
	 * @param createUser  the value for press_release_access_history.CREATE_USER
	 * @mbg.generated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_access_history.CREATE_DATETIME
	 * @return  the value of press_release_access_history.CREATE_DATETIME
	 * @mbg.generated
	 */
	public Date getCreateDatetime() {
		return createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_access_history.CREATE_DATETIME
	 * @param createDatetime  the value for press_release_access_history.CREATE_DATETIME
	 * @mbg.generated
	 */
	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_access_history.UPDATE_USER
	 * @return  the value of press_release_access_history.UPDATE_USER
	 * @mbg.generated
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_access_history.UPDATE_USER
	 * @param updateUser  the value for press_release_access_history.UPDATE_USER
	 * @mbg.generated
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_access_history.UPDATE_DATETIME
	 * @return  the value of press_release_access_history.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_access_history.UPDATE_DATETIME
	 * @param updateDatetime  the value for press_release_access_history.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_access_history
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", mediaUserId=").append(mediaUserId);
		sb.append(", accessIp=").append(accessIp);
		sb.append(", accessTime=").append(accessTime);
		sb.append(", readerType=").append(readerType);
		sb.append(", deleteFlag=").append(deleteFlag);
		sb.append(", createUser=").append(createUser);
		sb.append(", createDatetime=").append(createDatetime);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updateDatetime=").append(updateDatetime);
		sb.append("]");
		return sb.toString();
	}
}