package com.jp.sense.pr.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table press_release_image
 */
public class PressReleaseImage extends PressReleaseImageKey {

	/**
	 * Database Column Remarks: 画像ファイル名 This field was generated by MyBatis Generator. This field corresponds to the database column press_release_image.IMAGE_NAME
	 * @mbg.generated
	 */
	private String imageName;
	/**
	 * Database Column Remarks: 画像高さ This field was generated by MyBatis Generator. This field corresponds to the database column press_release_image.IMAGE_HEIGHT
	 * @mbg.generated
	 */
	private String imageHeight;
	/**
	 * Database Column Remarks: 画像幅 This field was generated by MyBatis Generator. This field corresponds to the database column press_release_image.IMAGE_WIDTH
	 * @mbg.generated
	 */
	private String imageWidth;
	/**
	 * Database Column Remarks: 画像配置:1:左 2:中央 3:右 This field was generated by MyBatis Generator. This field corresponds to the database column press_release_image.IMAGE_PLACEMENT
	 * @mbg.generated
	 */
	private String imagePlacement;
	/**
	 * Database Column Remarks: マインフラグ This field was generated by MyBatis Generator. This field corresponds to the database column press_release_image.MAIN_FLAG
	 * @mbg.generated
	 */
	private String mainFlag;
	/**
	 * Database Column Remarks: 画像キャプション This field was generated by MyBatis Generator. This field corresponds to the database column press_release_image.IMAGE_CAPTION
	 * @mbg.generated
	 */
	private String imageCaption;
	/**
	 * Database Column Remarks: 削除フラグ This field was generated by MyBatis Generator. This field corresponds to the database column press_release_image.DELETE_FLAG
	 * @mbg.generated
	 */
	private String deleteFlag;
	/**
	 * Database Column Remarks: 作成者 This field was generated by MyBatis Generator. This field corresponds to the database column press_release_image.CREATE_USER
	 * @mbg.generated
	 */
	private String createUser;
	/**
	 * Database Column Remarks: 作成日時:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column press_release_image.CREATE_DATETIME
	 * @mbg.generated
	 */
	private Date createDatetime;
	/**
	 * Database Column Remarks: 最終更新者 This field was generated by MyBatis Generator. This field corresponds to the database column press_release_image.UPDATE_USER
	 * @mbg.generated
	 */
	private String updateUser;
	/**
	 * Database Column Remarks: 最終更新日時:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column press_release_image.UPDATE_DATETIME
	 * @mbg.generated
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_image.IMAGE_NAME
	 * @return  the value of press_release_image.IMAGE_NAME
	 * @mbg.generated
	 */
	public String getImageName() {
		return imageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_image.IMAGE_NAME
	 * @param imageName  the value for press_release_image.IMAGE_NAME
	 * @mbg.generated
	 */
	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_image.IMAGE_HEIGHT
	 * @return  the value of press_release_image.IMAGE_HEIGHT
	 * @mbg.generated
	 */
	public String getImageHeight() {
		return imageHeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_image.IMAGE_HEIGHT
	 * @param imageHeight  the value for press_release_image.IMAGE_HEIGHT
	 * @mbg.generated
	 */
	public void setImageHeight(String imageHeight) {
		this.imageHeight = imageHeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_image.IMAGE_WIDTH
	 * @return  the value of press_release_image.IMAGE_WIDTH
	 * @mbg.generated
	 */
	public String getImageWidth() {
		return imageWidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_image.IMAGE_WIDTH
	 * @param imageWidth  the value for press_release_image.IMAGE_WIDTH
	 * @mbg.generated
	 */
	public void setImageWidth(String imageWidth) {
		this.imageWidth = imageWidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_image.IMAGE_PLACEMENT
	 * @return  the value of press_release_image.IMAGE_PLACEMENT
	 * @mbg.generated
	 */
	public String getImagePlacement() {
		return imagePlacement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_image.IMAGE_PLACEMENT
	 * @param imagePlacement  the value for press_release_image.IMAGE_PLACEMENT
	 * @mbg.generated
	 */
	public void setImagePlacement(String imagePlacement) {
		this.imagePlacement = imagePlacement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_image.MAIN_FLAG
	 * @return  the value of press_release_image.MAIN_FLAG
	 * @mbg.generated
	 */
	public String getMainFlag() {
		return mainFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_image.MAIN_FLAG
	 * @param mainFlag  the value for press_release_image.MAIN_FLAG
	 * @mbg.generated
	 */
	public void setMainFlag(String mainFlag) {
		this.mainFlag = mainFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_image.IMAGE_CAPTION
	 * @return  the value of press_release_image.IMAGE_CAPTION
	 * @mbg.generated
	 */
	public String getImageCaption() {
		return imageCaption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_image.IMAGE_CAPTION
	 * @param imageCaption  the value for press_release_image.IMAGE_CAPTION
	 * @mbg.generated
	 */
	public void setImageCaption(String imageCaption) {
		this.imageCaption = imageCaption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_image.DELETE_FLAG
	 * @return  the value of press_release_image.DELETE_FLAG
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_image.DELETE_FLAG
	 * @param deleteFlag  the value for press_release_image.DELETE_FLAG
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_image.CREATE_USER
	 * @return  the value of press_release_image.CREATE_USER
	 * @mbg.generated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_image.CREATE_USER
	 * @param createUser  the value for press_release_image.CREATE_USER
	 * @mbg.generated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_image.CREATE_DATETIME
	 * @return  the value of press_release_image.CREATE_DATETIME
	 * @mbg.generated
	 */
	public Date getCreateDatetime() {
		return createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_image.CREATE_DATETIME
	 * @param createDatetime  the value for press_release_image.CREATE_DATETIME
	 * @mbg.generated
	 */
	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_image.UPDATE_USER
	 * @return  the value of press_release_image.UPDATE_USER
	 * @mbg.generated
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_image.UPDATE_USER
	 * @param updateUser  the value for press_release_image.UPDATE_USER
	 * @mbg.generated
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_image.UPDATE_DATETIME
	 * @return  the value of press_release_image.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_image.UPDATE_DATETIME
	 * @param updateDatetime  the value for press_release_image.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_image
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", imageName=").append(imageName);
		sb.append(", imageHeight=").append(imageHeight);
		sb.append(", imageWidth=").append(imageWidth);
		sb.append(", imagePlacement=").append(imagePlacement);
		sb.append(", mainFlag=").append(mainFlag);
		sb.append(", imageCaption=").append(imageCaption);
		sb.append(", deleteFlag=").append(deleteFlag);
		sb.append(", createUser=").append(createUser);
		sb.append(", createDatetime=").append(createDatetime);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updateDatetime=").append(updateDatetime);
		sb.append("]");
		return sb.toString();
	}
}