package com.jp.sense.pr.model.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table press_release_access_history
 */
public class PressReleaseAccessHistoryKey {

	/**
	 * Database Column Remarks: アクセス履歴ID This field was generated by MyBatis Generator. This field corresponds to the database column press_release_access_history.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: プレスリリースID This field was generated by MyBatis Generator. This field corresponds to the database column press_release_access_history.PRESS_RELEASE_ID
	 * @mbg.generated
	 */
	private Integer pressReleaseId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_access_history.ID
	 * @return  the value of press_release_access_history.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_access_history.ID
	 * @param id  the value for press_release_access_history.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release_access_history.PRESS_RELEASE_ID
	 * @return  the value of press_release_access_history.PRESS_RELEASE_ID
	 * @mbg.generated
	 */
	public Integer getPressReleaseId() {
		return pressReleaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release_access_history.PRESS_RELEASE_ID
	 * @param pressReleaseId  the value for press_release_access_history.PRESS_RELEASE_ID
	 * @mbg.generated
	 */
	public void setPressReleaseId(Integer pressReleaseId) {
		this.pressReleaseId = pressReleaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release_access_history
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", pressReleaseId=").append(pressReleaseId);
		sb.append("]");
		return sb.toString();
	}
}