package com.jp.sense.pr.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table press_release
 */
public class PressRelease {

	/**
	 * Database Column Remarks: プレスリリースID This field was generated by MyBatis Generator. This field corresponds to the database column press_release.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 企業ID This field was generated by MyBatis Generator. This field corresponds to the database column press_release.BUSINESS_ID
	 * @mbg.generated
	 */
	private Integer businessId;
	/**
	 * Database Column Remarks: プレスリリースタイトル This field was generated by MyBatis Generator. This field corresponds to the database column press_release.RELEASE_TITLE
	 * @mbg.generated
	 */
	private String releaseTitle;
	/**
	 * Database Column Remarks: プレスリリースサブタイトル This field was generated by MyBatis Generator. This field corresponds to the database column press_release.RELEASE_SUB_TITLE
	 * @mbg.generated
	 */
	private String releaseSubTitle;
	/**
	 * Database Column Remarks: リリースリード文 This field was generated by MyBatis Generator. This field corresponds to the database column press_release.RELEASE_LEAD_WORD
	 * @mbg.generated
	 */
	private String releaseLeadWord;
	/**
	 * Database Column Remarks: リリース文体 This field was generated by MyBatis Generator. This field corresponds to the database column press_release.RELEASE_BODY
	 * @mbg.generated
	 */
	private String releaseBody;
	/**
	 * Database Column Remarks: メディア追加情報 This field was generated by MyBatis Generator. This field corresponds to the database column press_release.MEDIA_ADDITIONAL_INFO
	 * @mbg.generated
	 */
	private String mediaAdditionalInfo;
	/**
	 * Database Column Remarks: メディア関係者案内タイプ:1:報道問合せ先 2:取材案内 3:素材提供 4:サンプル提供 5:その他 This field was generated by MyBatis Generator. This field corresponds to the database column press_release.MEDIA_INFORMATION_TYPE
	 * @mbg.generated
	 */
	private String mediaInformationType;
	/**
	 * Database Column Remarks: 種類 This field was generated by MyBatis Generator. This field corresponds to the database column press_release.RELEASE_TYPE
	 * @mbg.generated
	 */
	private String releaseType;
	/**
	 * Database Column Remarks: ビジネスカテゴリID This field was generated by MyBatis Generator. This field corresponds to the database column press_release.BUSINESS_CATEGORY_ID
	 * @mbg.generated
	 */
	private Integer businessCategoryId;
	/**
	 * Database Column Remarks: ビジネスサブカテゴリID This field was generated by MyBatis Generator. This field corresponds to the database column press_release.BUSINESS_SUBCATEGORY_ID
	 * @mbg.generated
	 */
	private Integer businessSubcategoryId;
	/**
	 * Database Column Remarks: 関連URL This field was generated by MyBatis Generator. This field corresponds to the database column press_release.RELATED_URL
	 * @mbg.generated
	 */
	private String relatedUrl;
	/**
	 * Database Column Remarks: メディアリストID This field was generated by MyBatis Generator. This field corresponds to the database column press_release.MEDIA_LIST_ID
	 * @mbg.generated
	 */
	private Integer mediaListId;
	/**
	 * Database Column Remarks: 配信方法メール This field was generated by MyBatis Generator. This field corresponds to the database column press_release.DELIVER_METHOD_MAIL
	 * @mbg.generated
	 */
	private String deliverMethodMail;
	/**
	 * Database Column Remarks: 配信方法FAX This field was generated by MyBatis Generator. This field corresponds to the database column press_release.DELIVER_METHOD_FAX
	 * @mbg.generated
	 */
	private String deliverMethodFax;
	/**
	 * Database Column Remarks: メールタイトル This field was generated by MyBatis Generator. This field corresponds to the database column press_release.MAIL_TITLE
	 * @mbg.generated
	 */
	private String mailTitle;
	/**
	 * Database Column Remarks: メール本文先頭行 This field was generated by MyBatis Generator. This field corresponds to the database column press_release.MAIL_BODY_LEAD_TEXT
	 * @mbg.generated
	 */
	private String mailBodyLeadText;
	/**
	 * Database Column Remarks: メディア配信 This field was generated by MyBatis Generator. This field corresponds to the database column press_release.DELIVER_MEDIA
	 * @mbg.generated
	 */
	private String deliverMedia;
	/**
	 * Database Column Remarks: ユーザー配信 This field was generated by MyBatis Generator. This field corresponds to the database column press_release.DELIVER_USER
	 * @mbg.generated
	 */
	private String deliverUser;
	/**
	 * Database Column Remarks: メディア掲載 This field was generated by MyBatis Generator. This field corresponds to the database column press_release.PUBLISH_MEDIA
	 * @mbg.generated
	 */
	private String publishMedia;
	/**
	 * Database Column Remarks: リリースステータス:1:下書き保存 2:配信済み 3:非公開 This field was generated by MyBatis Generator. This field corresponds to the database column press_release.RELEASE_STATUS
	 * @mbg.generated
	 */
	private String releaseStatus;
	/**
	 * Database Column Remarks: 配信日:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column press_release.PUBLISHED_DATE
	 * @mbg.generated
	 */
	private Date publishedDate;
	/**
	 * Database Column Remarks: 削除フラグ This field was generated by MyBatis Generator. This field corresponds to the database column press_release.DELETE_FLAG
	 * @mbg.generated
	 */
	private String deleteFlag;
	/**
	 * Database Column Remarks: 作成者 This field was generated by MyBatis Generator. This field corresponds to the database column press_release.CREATE_USER
	 * @mbg.generated
	 */
	private String createUser;
	/**
	 * Database Column Remarks: 作成日時:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column press_release.CREATE_DATETIME
	 * @mbg.generated
	 */
	private Date createDatetime;
	/**
	 * Database Column Remarks: 最終更新者 This field was generated by MyBatis Generator. This field corresponds to the database column press_release.UPDATE_USER
	 * @mbg.generated
	 */
	private String updateUser;
	/**
	 * Database Column Remarks: 最終更新日時:YYYY/MM/DD HH:MM:SS This field was generated by MyBatis Generator. This field corresponds to the database column press_release.UPDATE_DATETIME
	 * @mbg.generated
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.ID
	 * @return  the value of press_release.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.ID
	 * @param id  the value for press_release.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.BUSINESS_ID
	 * @return  the value of press_release.BUSINESS_ID
	 * @mbg.generated
	 */
	public Integer getBusinessId() {
		return businessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.BUSINESS_ID
	 * @param businessId  the value for press_release.BUSINESS_ID
	 * @mbg.generated
	 */
	public void setBusinessId(Integer businessId) {
		this.businessId = businessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.RELEASE_TITLE
	 * @return  the value of press_release.RELEASE_TITLE
	 * @mbg.generated
	 */
	public String getReleaseTitle() {
		return releaseTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.RELEASE_TITLE
	 * @param releaseTitle  the value for press_release.RELEASE_TITLE
	 * @mbg.generated
	 */
	public void setReleaseTitle(String releaseTitle) {
		this.releaseTitle = releaseTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.RELEASE_SUB_TITLE
	 * @return  the value of press_release.RELEASE_SUB_TITLE
	 * @mbg.generated
	 */
	public String getReleaseSubTitle() {
		return releaseSubTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.RELEASE_SUB_TITLE
	 * @param releaseSubTitle  the value for press_release.RELEASE_SUB_TITLE
	 * @mbg.generated
	 */
	public void setReleaseSubTitle(String releaseSubTitle) {
		this.releaseSubTitle = releaseSubTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.RELEASE_LEAD_WORD
	 * @return  the value of press_release.RELEASE_LEAD_WORD
	 * @mbg.generated
	 */
	public String getReleaseLeadWord() {
		return releaseLeadWord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.RELEASE_LEAD_WORD
	 * @param releaseLeadWord  the value for press_release.RELEASE_LEAD_WORD
	 * @mbg.generated
	 */
	public void setReleaseLeadWord(String releaseLeadWord) {
		this.releaseLeadWord = releaseLeadWord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.RELEASE_BODY
	 * @return  the value of press_release.RELEASE_BODY
	 * @mbg.generated
	 */
	public String getReleaseBody() {
		return releaseBody;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.RELEASE_BODY
	 * @param releaseBody  the value for press_release.RELEASE_BODY
	 * @mbg.generated
	 */
	public void setReleaseBody(String releaseBody) {
		this.releaseBody = releaseBody;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.MEDIA_ADDITIONAL_INFO
	 * @return  the value of press_release.MEDIA_ADDITIONAL_INFO
	 * @mbg.generated
	 */
	public String getMediaAdditionalInfo() {
		return mediaAdditionalInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.MEDIA_ADDITIONAL_INFO
	 * @param mediaAdditionalInfo  the value for press_release.MEDIA_ADDITIONAL_INFO
	 * @mbg.generated
	 */
	public void setMediaAdditionalInfo(String mediaAdditionalInfo) {
		this.mediaAdditionalInfo = mediaAdditionalInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.MEDIA_INFORMATION_TYPE
	 * @return  the value of press_release.MEDIA_INFORMATION_TYPE
	 * @mbg.generated
	 */
	public String getMediaInformationType() {
		return mediaInformationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.MEDIA_INFORMATION_TYPE
	 * @param mediaInformationType  the value for press_release.MEDIA_INFORMATION_TYPE
	 * @mbg.generated
	 */
	public void setMediaInformationType(String mediaInformationType) {
		this.mediaInformationType = mediaInformationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.RELEASE_TYPE
	 * @return  the value of press_release.RELEASE_TYPE
	 * @mbg.generated
	 */
	public String getReleaseType() {
		return releaseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.RELEASE_TYPE
	 * @param releaseType  the value for press_release.RELEASE_TYPE
	 * @mbg.generated
	 */
	public void setReleaseType(String releaseType) {
		this.releaseType = releaseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.BUSINESS_CATEGORY_ID
	 * @return  the value of press_release.BUSINESS_CATEGORY_ID
	 * @mbg.generated
	 */
	public Integer getBusinessCategoryId() {
		return businessCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.BUSINESS_CATEGORY_ID
	 * @param businessCategoryId  the value for press_release.BUSINESS_CATEGORY_ID
	 * @mbg.generated
	 */
	public void setBusinessCategoryId(Integer businessCategoryId) {
		this.businessCategoryId = businessCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.BUSINESS_SUBCATEGORY_ID
	 * @return  the value of press_release.BUSINESS_SUBCATEGORY_ID
	 * @mbg.generated
	 */
	public Integer getBusinessSubcategoryId() {
		return businessSubcategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.BUSINESS_SUBCATEGORY_ID
	 * @param businessSubcategoryId  the value for press_release.BUSINESS_SUBCATEGORY_ID
	 * @mbg.generated
	 */
	public void setBusinessSubcategoryId(Integer businessSubcategoryId) {
		this.businessSubcategoryId = businessSubcategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.RELATED_URL
	 * @return  the value of press_release.RELATED_URL
	 * @mbg.generated
	 */
	public String getRelatedUrl() {
		return relatedUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.RELATED_URL
	 * @param relatedUrl  the value for press_release.RELATED_URL
	 * @mbg.generated
	 */
	public void setRelatedUrl(String relatedUrl) {
		this.relatedUrl = relatedUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.MEDIA_LIST_ID
	 * @return  the value of press_release.MEDIA_LIST_ID
	 * @mbg.generated
	 */
	public Integer getMediaListId() {
		return mediaListId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.MEDIA_LIST_ID
	 * @param mediaListId  the value for press_release.MEDIA_LIST_ID
	 * @mbg.generated
	 */
	public void setMediaListId(Integer mediaListId) {
		this.mediaListId = mediaListId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.DELIVER_METHOD_MAIL
	 * @return  the value of press_release.DELIVER_METHOD_MAIL
	 * @mbg.generated
	 */
	public String getDeliverMethodMail() {
		return deliverMethodMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.DELIVER_METHOD_MAIL
	 * @param deliverMethodMail  the value for press_release.DELIVER_METHOD_MAIL
	 * @mbg.generated
	 */
	public void setDeliverMethodMail(String deliverMethodMail) {
		this.deliverMethodMail = deliverMethodMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.DELIVER_METHOD_FAX
	 * @return  the value of press_release.DELIVER_METHOD_FAX
	 * @mbg.generated
	 */
	public String getDeliverMethodFax() {
		return deliverMethodFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.DELIVER_METHOD_FAX
	 * @param deliverMethodFax  the value for press_release.DELIVER_METHOD_FAX
	 * @mbg.generated
	 */
	public void setDeliverMethodFax(String deliverMethodFax) {
		this.deliverMethodFax = deliverMethodFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.MAIL_TITLE
	 * @return  the value of press_release.MAIL_TITLE
	 * @mbg.generated
	 */
	public String getMailTitle() {
		return mailTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.MAIL_TITLE
	 * @param mailTitle  the value for press_release.MAIL_TITLE
	 * @mbg.generated
	 */
	public void setMailTitle(String mailTitle) {
		this.mailTitle = mailTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.MAIL_BODY_LEAD_TEXT
	 * @return  the value of press_release.MAIL_BODY_LEAD_TEXT
	 * @mbg.generated
	 */
	public String getMailBodyLeadText() {
		return mailBodyLeadText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.MAIL_BODY_LEAD_TEXT
	 * @param mailBodyLeadText  the value for press_release.MAIL_BODY_LEAD_TEXT
	 * @mbg.generated
	 */
	public void setMailBodyLeadText(String mailBodyLeadText) {
		this.mailBodyLeadText = mailBodyLeadText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.DELIVER_MEDIA
	 * @return  the value of press_release.DELIVER_MEDIA
	 * @mbg.generated
	 */
	public String getDeliverMedia() {
		return deliverMedia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.DELIVER_MEDIA
	 * @param deliverMedia  the value for press_release.DELIVER_MEDIA
	 * @mbg.generated
	 */
	public void setDeliverMedia(String deliverMedia) {
		this.deliverMedia = deliverMedia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.DELIVER_USER
	 * @return  the value of press_release.DELIVER_USER
	 * @mbg.generated
	 */
	public String getDeliverUser() {
		return deliverUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.DELIVER_USER
	 * @param deliverUser  the value for press_release.DELIVER_USER
	 * @mbg.generated
	 */
	public void setDeliverUser(String deliverUser) {
		this.deliverUser = deliverUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.PUBLISH_MEDIA
	 * @return  the value of press_release.PUBLISH_MEDIA
	 * @mbg.generated
	 */
	public String getPublishMedia() {
		return publishMedia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.PUBLISH_MEDIA
	 * @param publishMedia  the value for press_release.PUBLISH_MEDIA
	 * @mbg.generated
	 */
	public void setPublishMedia(String publishMedia) {
		this.publishMedia = publishMedia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.RELEASE_STATUS
	 * @return  the value of press_release.RELEASE_STATUS
	 * @mbg.generated
	 */
	public String getReleaseStatus() {
		return releaseStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.RELEASE_STATUS
	 * @param releaseStatus  the value for press_release.RELEASE_STATUS
	 * @mbg.generated
	 */
	public void setReleaseStatus(String releaseStatus) {
		this.releaseStatus = releaseStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.PUBLISHED_DATE
	 * @return  the value of press_release.PUBLISHED_DATE
	 * @mbg.generated
	 */
	public Date getPublishedDate() {
		return publishedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.PUBLISHED_DATE
	 * @param publishedDate  the value for press_release.PUBLISHED_DATE
	 * @mbg.generated
	 */
	public void setPublishedDate(Date publishedDate) {
		this.publishedDate = publishedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.DELETE_FLAG
	 * @return  the value of press_release.DELETE_FLAG
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.DELETE_FLAG
	 * @param deleteFlag  the value for press_release.DELETE_FLAG
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.CREATE_USER
	 * @return  the value of press_release.CREATE_USER
	 * @mbg.generated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.CREATE_USER
	 * @param createUser  the value for press_release.CREATE_USER
	 * @mbg.generated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.CREATE_DATETIME
	 * @return  the value of press_release.CREATE_DATETIME
	 * @mbg.generated
	 */
	public Date getCreateDatetime() {
		return createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.CREATE_DATETIME
	 * @param createDatetime  the value for press_release.CREATE_DATETIME
	 * @mbg.generated
	 */
	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.UPDATE_USER
	 * @return  the value of press_release.UPDATE_USER
	 * @mbg.generated
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.UPDATE_USER
	 * @param updateUser  the value for press_release.UPDATE_USER
	 * @mbg.generated
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column press_release.UPDATE_DATETIME
	 * @return  the value of press_release.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column press_release.UPDATE_DATETIME
	 * @param updateDatetime  the value for press_release.UPDATE_DATETIME
	 * @mbg.generated
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table press_release
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", businessId=").append(businessId);
		sb.append(", releaseTitle=").append(releaseTitle);
		sb.append(", releaseSubTitle=").append(releaseSubTitle);
		sb.append(", releaseLeadWord=").append(releaseLeadWord);
		sb.append(", releaseBody=").append(releaseBody);
		sb.append(", mediaAdditionalInfo=").append(mediaAdditionalInfo);
		sb.append(", mediaInformationType=").append(mediaInformationType);
		sb.append(", releaseType=").append(releaseType);
		sb.append(", businessCategoryId=").append(businessCategoryId);
		sb.append(", businessSubcategoryId=").append(businessSubcategoryId);
		sb.append(", relatedUrl=").append(relatedUrl);
		sb.append(", mediaListId=").append(mediaListId);
		sb.append(", deliverMethodMail=").append(deliverMethodMail);
		sb.append(", deliverMethodFax=").append(deliverMethodFax);
		sb.append(", mailTitle=").append(mailTitle);
		sb.append(", mailBodyLeadText=").append(mailBodyLeadText);
		sb.append(", deliverMedia=").append(deliverMedia);
		sb.append(", deliverUser=").append(deliverUser);
		sb.append(", publishMedia=").append(publishMedia);
		sb.append(", releaseStatus=").append(releaseStatus);
		sb.append(", publishedDate=").append(publishedDate);
		sb.append(", deleteFlag=").append(deleteFlag);
		sb.append(", createUser=").append(createUser);
		sb.append(", createDatetime=").append(createDatetime);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updateDatetime=").append(updateDatetime);
		sb.append("]");
		return sb.toString();
	}
}